### ISSUE TITLE
Is BeginnerTutorial with yield all correct? 

### ISSUE THREAD

**Issue by mauron85** [redux-saga/redux-saga#1044]
I'm using redux-saga with typescript and trying very basic example from
https://redux-saga.js.org/docs/introduction/BeginnerTutorial.html

This will not compile with typescript

```
import { SagaIterator } from 'redux-saga';
import { all, takeEvery, call } from 'redux-saga/effects';

// Our watcher Saga: spawn a new incrementAsync task on each INCREMENT_ASYNC
export function* watchIncrementAsync(): SagaIterator {
  yield takeEvery('INCREMENT_ASYNC', incrementAsync)
}

// single entry point to start all Sagas at once
export default function* rootSaga() {
  yield all([
    helloSaga(),
    watchIncrementAsync()
  ])
}
```

It produces typescript error:
```
(16,13): error TS2345: Argument of type 'IterableIterator<AllEffect | RootEffect | TakeEffect | ChannelTakeEffect<any> | PutEffect<any> | ...' is not assignable to parameter of type '{ [key: string]: Effect; }'.
  Index signature is missing in type 'IterableIterator<AllEffect | RootEffect | TakeEffect | ChannelTakeEffect<any> | PutEffect<any> | ...'.
```

However adding `call` doesn't produce any type error.
```
  yield all([ call(saga) ]);
```

I'm wondering if there is problem with type definitions or what I'm doing wrong.

**Comment by Andarist** [comment]
cc @aikoven

**Comment by aikoven** [comment]
Current typings were designed to protect users from yielding function calls directly, but use effects instead. This way we catch situations where you unintentionally introduce side-effect in your saga forgetting to wrap function call with effect.

IMO the example should be updated to use more idiomatic way:
```js
// single entry point to start all Sagas at once
export default function* rootSaga() {
  yield all([
    call(helloSaga),
    call(watchIncrementAsync)
  ])
}
```

Otherwise, we could try to solve it like in https://github.com/redux-saga/redux-saga/pull/770, i. e. to make the strictness opt-in by declaring the return type of generator to be `SagaIterator`.

**Comment by Andarist** [comment]
If similar issue got fixed like mentioned, we should prefer consistency and do the same for this case too.

**Comment by aikoven** [comment]
Fixed in https://github.com/redux-saga/redux-saga/pull/1047
