### ISSUE TITLE
How to handle redux saga error in the wrapper?

### ISSUE THREAD

**Issue by kimjuny** [redux-saga/redux-saga#1050]
This is the Normal Way:

```javascript
function* saga1() {
  try {
    // do stuff
  } catch (err) {
    // handle err
  }
}

function* saga2() {
  try {
  } catch (err) {
  }
}

function* wrapper() {
  yield [
    takeLatest('saga1', saga1),
    takeLatest('saga2', saga2),
  ];
}
```

This is Expected Way:

```javascript
function* saga1() {
}

function* saga2() {
}

function* wrapper() {
  try {
    yield [
      takeLatest('saga1', saga1),
      takeLatest('saga2', saga2),
    ];
  } catch (err) {
    // handle errors
  }
}
```
Is there anyway to achieve above way to handle errors? Using normal way sometimes leading to repeatedly handle same error (witch means duplicated codes).

**Comment by Andarist** [comment]
This is not possible. `takeLatest` (and `takeEvery` and `throttle`) are just thin wrappers on `fork` effect which is non-blocking.

The way it works is that for a non-blocking effect your saga continues after executing it, so wrapping it like that is not possible because your saga `wrapper` saga will be already paused at the very end of itself - basically after `try/catch` block so even if we'd tried to support such thing we wouldnt be able to throw inside ur `wrapper` saga in such a way that it would active this `try/catch`.

If you want to dedupe ur logic I suggest to make a higher order saga such as:
```js
const safe = (recovery, saga, ...args) => function* (action) {
	try {
		yield call(saga, ...args, action)
	} catch (err) {
		yield call(recovery, ...args, err)
	}	
}
```

which you could use like this
```js
function* saga1() {}

function* saga2() {}

function* wrapper() {
  const recovery = err => console.log('caught', err)

  yield [
    takeLatest('saga1', safe(recovery, saga1)),
    takeLatest('saga2', safe(recovery, saga2)),
  ];
}
```

**Comment by alanhg** [comment]
@kimjuny Andarist
Is there a way to configure globally?
