### ISSUE TITLE
Using takeLatest on a channel doesn't work

### ISSUE THREAD

**Issue by erikvold** [redux-saga/redux-saga#1063]
Code:

```javascript
const channel = yield actionChannel(TYPE);
yield takeLatest(channel);
```

Expected:

works

Actual:

I got this error:

```
index.js: uncaught at mainSaga 
 at watchForSubmit
 at takeLatest 
 TypeError: Cannot read property 'name' of undefined
```

**Comment by Andarist** [comment]
Could u share a reproduced issue on something like https://codesandbox.io/ ?

**Comment by camflan** [comment]
Is `takeLatest` supposed to work with channels? I've haven't seen this before and there are no tests or documentation written about this. If it's supposed to be supported, we should add tests and documentation too.

**Comment by Andarist** [comment]
Should work just fine as `takeLatest` (and `takeEvery`) are implemented using regular `take` which ofc accepts a channel as argument. 

**docs + tests**
Noted. Would love to get some help on this *wink*

**Comment by Andarist** [comment]
@erikvold 

`yield takeLatest(channel);` - this probably is not working because u have not passed in any generator, u need to provide a saga handler for this `takeLatest`

**Comment by erikvold** [comment]
@Andarist I updated my example, how should it be change based on your comment?

**Comment by erikvold** [comment]
ah it looks like `takeLatest` is not meant to do what I want it to do, it's a non-blocking call effect, I was expected it to be a blocking effect when used with a channel.

**Comment by erikvold** [comment]
seems like `takeLatest` should be called `forkLatest` to me.

**Comment by Andarist** [comment]
well, it probably be even `takeAndForkLatest` or smth :D 

> I was expected it to be a blocking effect when used with a channel.

How did you want to use it (code-wise)?

> @Andarist I updated my example, how should it be changed based on your comment?

I think you might find this useful:
```js
const channel = yield actionChannel(TYPE, buffers.sliding(1));
// ...
const action = yield take(channel);
```

`throttle` helper is implemented under the hood using those. 

If you share what outcome are you reaching for (requirements) I might be able to advise more :)

**Comment by Amareis** [comment]
How about takeEvery? Is it works as expected with channels?

**Comment by Andarist** [comment]
@Amareis both - `takeEvery` and `takeLatest` - work fine with channel. @erikvold had concerns about the naming of those, because from the names he has expected different behaviour.

You can check out equivalent implementations of those helpers in [the docs](https://redux-saga.js.org/docs/api/index.html). Even though they mention only `pattern` as argument, its passed down to normal `take` which ofc can be used without problems with channels.

This issue got a little bit stale, so I'm closing it. If you both have any questions, remarks, whatever - just write here or open a new one, I will always get back to you.
