### ISSUE TITLE
Call mistaking response and never returning.

### ISSUE THREAD

**Issue by bradennapier** [redux-saga/redux-saga#1072]
Hey y'all!  As I'm sure you know I am a HUGE fan of `redux-saga` so thanks for the continued work on the package!

So what is it that determines if a call should be resolved?  I know it should be "if a promise is returned" but in my case it appears that `yield call` is mistaking one of my libraries for a promise.  How are you checking to determine how to handle this?

In my case I am doing something like this:

```js
const observer = yield call([auth, auth.startForgotPassword], username);
```

and it can simply return the "observer"

```js
const observer = new PromiseQueue();
return observer
```

and it will never resolve.

The observer itself actually does implement a "next" method which I just realized is almost certainly the issue as the next() will return a promise as well.  Is there anyway to tag redux-sagas generators in a way to avoid these types of conflicts?

**Comment by bradennapier** [comment]
To be a bit more clear, here is the code for the given library (which is just a wrapper around [promise-queue-observable](https://github.com/Dash-OS/promise-queue-observable)  which provides a buffer / channel similar to the redux-saga api's but with a few different semantics.  In this case returning the instance of the library directly will cause the issue.

I see that some properties are also being added to the instance when this occurs. 

In the end all it does is producers publish() promises and consumers get promises (.next()) 

```js
import PromiseQueue from 'promise-queue-observable';

import { CANCEL } from 'redux-saga';

export default class SagaObservable {
  constructor(config = {}) {
    this.observable = new PromiseQueue({
      ...config,
      promiseFactory: promise => {
        if (config.promiseFactory) {
          promise = config.promiseFactory(promise);
        }
        promise[CANCEL] = () => {
          this.observable.cancel();
        };
        return promise;
      },
    });
  }
  next = () => this.observable.next();
  publish = (...args) => this.observable.publish(...args);
  cancel = () => this.observable.cancel();
  cancelled = () => this.observable.cancelled();
}
```

**Comment by Andarist** [comment]
You can check whats getting checked against `call`'s result [here](https://github.com/redux-saga/redux-saga/blob/bdc47bf10af1da147349cffa72fd9b096a90e747/src/internal/proc.js#L494). 

It shouldnt be mistaken for promise as it would incline `result` to have `then` method. That is not the case. I was worried that it was mistaken for `iterator` (because of the `next` method), but we check not only for `next` but also for `throw` method.

From my perspective it should work, could u prepare a quick demo on something like https://codesandbox.io/ so I could debug this? Would greatly appreciate it.

**Comment by bradennapier** [comment]
Ahh, PromiseQueue itself actually has throw and next methods.  The example above does not -- which is what I use 90% of the time, but the PromiseQueue that the above uses just happens to be what I was using instead this time.

**Comment by bradennapier** [comment]
Ok here is a simple example.  Obviously this doesnt make much sense -- but it doesnt increment because it is waiting on observer itself which is the response of the createObserver function.  If you simply change that so the observer is instead created in the main body it works no problem

https://codesandbox.io/s/Z6xAqZng6

**Comment by Andarist** [comment]
Sorry for not responding any sooner. I don't know how, but I've missed your reply. 

Unfortunately due to JavaScript limitations, present conventions etc it seems the best option for us to detect if something is 'thenable' to classify it as a promise. Symbols are also not yet that mainstream and even native promises do not expose any promise-relate promise.

I guess you have resolved your issue by now, but I advise anyhow not to use `.then` method on your classes, because many other libraries would also think it is a promise and that could lead to some nasty bugs.

If you have any other questions, please just ask in this thread or create a new one.
