### ISSUE TITLE
Errors from event channels can't be caught in sagas

### ISSUE THREAD

**Issue by ethanroday** [redux-saga/redux-saga#1106]
### Example
Link: https://jsbin.com/xuhinegebo/edit?js,console
This example is slightly modified from the event channel example in the `redux-saga` [channel docs](https://redux-saga.js.org/docs/advanced/Channels.html). There are two important differences in the `countdown()` function:
1. The count goes down by twos instead of ones.
2. When the counter value is less than zero, an error is thrown.
Thus, when `secs` is even, the countdown proceeds and the channel closes as normal. When `secs` is odd, though, an error is thrown.

### Expected Behavior
In `countdownSaga()`, I expect the `catch` block in the `try`/`catch`/`finally` construct to handle the error propagating up from the event channel, log the error, and close the channel.

### Observed Behavior
Instead, the error doesn't even seem to be recognized by `countdownSaga()`. Neither the `catch` nor `finally` block is executed, and the error bubbles up to the top level.
In fact, since the channel is created with `setInterval()` and then never cancelled, it just keeps generating a new error every second _forever_.

I realize there has been a lot of discussion about error handling in `redux-saga`, and that this issue is probably related to many of them. In the meantime, has anyone discovered a workaround for this particular problem?

**Comment by Andarist** [comment]
Thanks for reaching out. Im afraid that described expected behaviour just isnt possible in javascript (without hackery on `setInterval` - which we wont do).

You `setInterval` just runs in completely different execution context and `redux-saga` has no knowledge nor power over it.

I would suggest you to wrap your `setInterval` code in a `try/catch` and `emit(END)` from the `catch` block.

**Comment by ethanroday** [comment]
@Andarist Is that something specific to `setInterval()`, or are you saying that's just the nature of any async source of events (like, say, an Observable)? So there's no way to have the saga handle errors which originate in the channel?

**Comment by Andarist** [comment]
> @Andarist Is that something specific to setInterval(), or are you saying that's just the nature of any async source of events (like, say, an Observable)? 

Yeah, though with observables it would be possible to implement if you'd returned observable from the `eventChannel` factory, but then it wouldnt be possible to auto-unsubscribe when calling `chan.close()`.

> So there's no way to have the saga handle errors which originate in the channel?

As what happens in the `eventChannel` is async AND outside of the `redux-saga` control flow - its not possible to catch those errors on our side. Catching `call`'s errors (like when making a request to API) is possible only because the actual execution of the call is handed to the `redux-saga` and it can hook up into i.e. promise error handling so it can throw the caught error back to you.

**Comment by ethanroday** [comment]
Hm okay. Thanks for the explanation. In that case, it may be helpful to add something to the channel docs about error handling.
