### ISSUE TITLE
[Bug] Effects "throttle" and "takeEvery" accept action sequence

### ISSUE THREAD

**Issue by hapood** [redux-saga/redux-saga#1165]
saga:

```javascript
import { throttle, takeEvery} from "redux-saga/effects";

function* f1(){
  console.log('f1')
}

function* f2(){
  console.log('f2')
}

export default function* () {
  yield takeEvery('ACTION1', f1);
  yield throttle(1000, 'ACTION2', f2);
}
```

call actions:

```javascript
store.dispatch('ACTION1')
store.dispatch('ACTION2')
```

In my opinion, the result should be "f1 f2", because I called "ACTION1" first. But the true result is "f2 f1".
If I replace "throttle" with "takeEvery", result changed to "f1 f2".
Is it a bug?

**Comment by Andarist** [comment]
Could u setup a codesandbox.io or something so I could look on the live code and debug this quickly?

**Comment by hapood** [comment]
@Andarist Weird, this phenomenon disappeared when I build a small project. I will post a codesandbox.io url when I can recurrent it.

**Comment by Andarist** [comment]
I have once encountered something at least similar in the past, ive debugged it quite a bit but couldnt get to the bottom of the issue because had to move on to different matters.

Depending on the ordering is rather undesired and should be avoided. That being said once this PR get merged https://github.com/redux-saga/redux-saga/pull/824 it should resolve your issue. Although I wouldn't rely on the ordering even then.
