### ISSUE TITLE
Logging errors in Firefox

### ISSUE THREAD

**Issue by russiancow** [redux-saga/redux-saga#1180]
When an error is uncaught while `put`ing and action from a saga, redux-saga catches the error and logs it to the console ([line 475 in proc.js](https://github.com/redux-saga/redux-saga/blob/19d0e4ea0f5925015f7269d5a5de189d4685747a/src/internal/proc.js#L475)). This is great, except it defaults to only logging `error.stack` if that property exists, and Firefox doesn't show the error message on that property, which means I don't actually see the message in Firefox:

![image](https://user-images.githubusercontent.com/1589155/30760837-ae63a8b8-9f90-11e7-92c2-8087f0302d77.png)

For reference, Chrome works how I would expect:

![image](https://user-images.githubusercontent.com/1589155/30760958-4f629ae4-9f91-11e7-847d-39eccc3b5903.png)

If I change that line to always just log the error object instead of its `stack` or `message` properties, Firefox behaves as expected:

![image](https://user-images.githubusercontent.com/1589155/30760983-7e55297a-9f91-11e7-82d2-e5a0271362bc.png)

Are there any negative side effects to implementing this change? I can submit the PR, but I want to make sure that I won't inadvertently break any expected behavior before I do so.

Thanks!

**Comment by Andarist** [comment]
I have unified error logging in [this commit](https://github.com/redux-saga/redux-saga/commit/d23315cecaa97429c7bcd8bd7fa2cabf996510c1). Hope this fixes your issue, I'm gonna release this soon.

Sorry for not reaching back to you any sooner.

**Comment by russiancow** [comment]
Awesome, thanks so much! No worries about the late response.

**Comment by russiancow** [comment]
@Andarist I just updated redux-saga to 0.16.0 and I'm still getting the same issue, although only sometimes... Other times it works as I expect. I'm not sure what the pattern is, but I just got a stack trace today that looks like this:

![image](https://user-images.githubusercontent.com/1589155/32062839-8237b19e-ba2a-11e7-941b-d6ca8cc15287.png)

I can do some debugging on my end to figure out when/why it's not showing the error message, because it works correctly about half the time now; I just wanted to let you know and see if you were aware of the issue.

**Comment by Andarist** [comment]
Not really, I'm not aware about this issue. I'm trying to normalize errors [here](https://github.com/redux-saga/redux-saga/blob/026cd95f8ba888a018ce895ac1bbd1404c7bcdf4/src/internal/proc.js#L167).

Im preparing v1 and I want to drop this part of the code entirely, it is not our job to normalize browser quirks like this. Unfortunately error's stack property is not standardized yet ([they might be some day](https://github.com/tc39/proposal-error-stacks)) and they are not consistent across browsers.

I realize that debugging sagas might not be the easiest thing, because stack traces are quite enigmatic (although if you are proficient with using the debugger, it is not that hard to get what you want if you setup breakpoints). That's why [I want to create a babel plugin](https://github.com/redux-saga/redux-saga/issues/1199) that could be used during development - React does it and component stack traces are quite nice, same thing could be done with sagas to achieve saga traces. Please provide some feedback about the idea in the other thread about what type of information would be useful for you in such a babel-generated error.

**Comment by russiancow** [comment]
Hmm, interesting, I actually had no idea React had a Babel plugin for this. What you said about not wanting to deal with normalizing errors makes sense, so I'm in favor of the Babel plugin. I'm not sure what other information I would find useful besides the saga stack and source line numbers, so I'll have to think on that a bit. Thanks for the response!

**Comment by russiancow** [comment]
@Andarist I've given this a fair bit of though, and while I don't disagree with the notion of not wanting to normalize error logging across browsers, I think the original, unmodified error *has* to be  thrown (or at least logged) along with whatever saga error. I think React does a good job of this in the latest version, where it first throws a React error with the component stack information, and then throws the original error immediately afterwards:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/1589155/34271666-2641a3b0-e642-11e7-9e6e-e300a4452f42.png">
What are your thoughts? Let me know if there's another, more specific issue for error logging in general.

**Comment by Andarist** [comment]
Hm, I think it's nice approach that React has there, would have to check how they throw two errors at the "same time".

**Comment by russiancow** [comment]
I looked into it. For development, they just [call `console.error`](https://github.com/facebook/react/blob/642a678a80af9c2350aea2f8c816085b1aa98d45/packages/react-reconciler/src/ReactFiberErrorLogger.js#L65-L74) to log their own component error message (the one you see at the top of the screenshot above), but use [an interesting approach](https://github.com/facebook/react/blob/642a678a80af9c2350aea2f8c816085b1aa98d45/packages/shared/ReactErrorUtils.js#L130-L276) involving a fake DOM node and a custom error event/handler to throw the original error synchronously in a way that plays nicely with browser dev tools and preserves the flow of execution. For redux-saga, that may be overkill initially and you could probably just use `console.error` on the original error as well, but I can see how React's solution would be pretty powerful since you could properly trigger a "Pause on exceptions" breakpoint via dev tools.

Either way, for the time being, my suggestion would be to just log the saga error and original error back-to-back, so at least they both get printed to the console as intended, and you don't have to do any parsing at all of the error object. I can make that PR if you would like.

**Comment by Andarist** [comment]
I would love a PR, although I'm not sure what kind of PR to the master branch could you send regarding this **right now**. From what I remember the custom error wrapping got removed, so there is no need to `console.error` smth and throw something else because there is only one thing that need to be tackled. 

It got removed because I plan to sit down and work on the mentioned babel plugin and the supporting implementation in the redux-saga's core. In fact @restrry even has started working on this and I plan to review this this week to see what's left to do. Having this released would make great end of the year 😄 

As to React's approach - that's neat idea, I've even sent a PR once to this exact piece of code, but didn't thought of using this strategy myself anywhere. Seems like a thing worth exploring.

If you have any idea how the situation can be improved or you want to help in any way, dont hesitate before making issues or PRs. I really appreciate any help offers I can get 👍

**Comment by russiancow** [comment]
Ah okay, I didn't realize you changed this further on the master branch since 0.16.0. So then I guess there is no need for a PR in the short term. :) Having said that, I am interested in contributing to redux-saga's error handling, so I will play around with using React's approach and see if I can make it work for this library, and if I can, I will open a PR.

Thank you for your time! I love this library and would be happy to do whatever I can to help.
