### ISSUE TITLE
redux-saga crashed react-native

### ISSUE THREAD

**Issue by jhessin** [redux-saga/redux-saga#1218]
Whenever I try to use redux-saga in my react-native app I get the following screen.
![simulator screen shot - iphone x - 2017-10-22 at 09 53 19](https://user-images.githubusercontent.com/6241466/31863720-e8113e78-b70e-11e7-8a42-f929a5871e1d.png)

No clue why - any ideas? All I'm doing is the simple test saga:

`export function* helloSaga() {
  console.log('Hello Sagas!');
}
`

I'm following the tutorial and this is my redux/index.js file:
```
import { createStore, applyMiddleware } from 'redux';
import createSagaMiddleware from 'redux-saga';

import reducers from './reducers';
import { helloSaga } from './sagas'; // <-- ERROR TRIGGERS HERE!

export types from './types';
export * as actions from './actions';

const sagaMiddleware = createSagaMiddleware();
const store = createStore(
  reducers,
  applyMiddleware(sagaMiddleware)
);

sagaMiddleware.run(helloSaga);

export default store;

```

**Comment by jhessin** [comment]
FYI my project can be found [here](https://github.com/jhessin/BigButtonLists/tree/sagas)

**Comment by jhessin** [comment]
Okay this is a workaround (why this is necessary I don't know):

```
export const helloSaga = function* () {
  yield console.log('Hello Sagas!');
};
```

**Comment by Andarist** [comment]
Actually the problem is different. It's described at the bottom of [this section](https://github.com/redux-saga/redux-saga#using-umd-build-in-the-browser)

Just add at the top of your entry file
```js
import 'regenerator-runtime/runtime'
```

**Comment by jhessin** [comment]
I added the line to my redux/index.js file at the very top and get the same error as before. The only way I can avoid the error is to use the const _ = function* syntax as stated previously.

Again not sure why this is.

**Comment by Andarist** [comment]
Have you installed `regenerator-runtime` module?

**Comment by jhessin** [comment]
yes - 

package.json
```
{
  "name": "bigbuttonlists",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "@expo/vector-icons": "^5.2.0",
    "expo": "^21.0.0",
    "firebase": "^4.6.0",
    "native-base": "^2.3.3",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "react-native-easy-grid": "^0.1.15",
    "react-navigation": "^1.0.0-beta.13",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0",
    "redux-saga-firebase": "^0.6.1",
    "regenerator-runtime": "^0.11.0"
  },
  "devDependencies": {
    "eslint-config-rallycoding": "^3.2.0",
    "eslint-plugin-redux-saga": "^0.5.0"
  }
}

```

**Comment by Andarist** [comment]
That is weird, although the issue is not redux-saga's issue per se, I can have look at your project, but you would have to:
- push out the most recent work
- provide the instruction how to run it (im not using react-native and had some issues in the past with configuring given projects)

**Comment by jhessin** [comment]
Okay everything is up to date now - including readme. If you are just testing this aspect you can feel free to remove the reference to keys.js in the redux/sagas.js file. I haven't started using it anyway.

**Comment by Andarist** [comment]
So that is your transpiled file (only the very top of it):
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.watchLists = exports.ListDown = exports.listUp = exports.listModified = exports.listRemoved = exports.listAdded = undefined;
exports.rootSaga = rootSaga;

var _firebase = require(842       ); // 842 = firebase

var _firebase2 = babelHelpers.interopRequireDefault(_firebase);

var _reduxSagaFirebase = require(987                  ); // 987 = redux-saga-firebase

var _reduxSagaFirebase2 = babelHelpers.interopRequireDefault(_reduxSagaFirebase);

var _reduxSaga = require(821         ); // 821 = redux-saga

var _effects = require(835                 ); // 835 = redux-saga/effects

var _types = require(839      ); // 839 = ./types

var _types2 = babelHelpers.interopRequireDefault(_types);

var _marked = regeneratorRuntime.mark(rootSaga);

var regeneratorRuntime = require(444                  ); // 444 = regenerator-runtime
```

As you may notice `regeneratorRuntime` is used before being required. This is an issue between regenerator-transform and react-native preset. The import for the `regeneratorRuntime` is inserted by you version of react-native preset. Newer version should not behave like this, as [this commit](https://github.com/facebook/react-native/commit/2172bb4acb43c29d34c8bf438a0165ca0139e66f#diff-29bf9e3e60ddeda0cb13ebac5329e718) removed the inserting transform.

Why are things hoisted?
- require imports are hoisted to the top of the file, because its how es6 modules behave
- `regeneratorRuntime.mark` is also hoisted when you transpile generator function declarations, because its how declaractions work, right? you can use functions before they appear in the source code

So 2 **independent** transforms are hoisting here 2 different things and it just doesnt play well together. The issue was previously reported many times, i.e. [here](https://github.com/facebook/regenerator/issues/304). But Im not actually sure which project should fix it - probably babel. There is upcoming babel7 release which I hope should fix it altogether.

You need to upgrade your packages or use a custom (copied from the one you are using already) babel preset.
