### ISSUE TITLE
Allow using frozen actions

### ISSUE THREAD

**Issue by Alxandr** [redux-saga/redux-saga#1254]
I just updated redux-saga, to have everything break because we're using frozen actions. The `wrapSagaDispatch` fails when trying to expand our actions that are frozen.

Also, they make the actions non FSA compliant. This should really be optional.

**Comment by Andarist** [comment]
Hi there! This high-level thing here cannot be optional, because it helps us in distinguishing saga-induces actions from the others and that helps with some edge cases in scheduling.

However I was looking at this 'hack' recently and Im very interested in changing it, because it's a little bit gross. Ideally I would just use `Set` for storing those actions temporarily, but I do not want to require people loading polyfills to support old environments. Any ideas how this could be solved? There is always possibility to store them in an array, but Im wondering if some better, maybe more performant, solution could be found.

**Comment by Alxandr** [comment]
If the action is extensible or have a meta property that is extensible, add it there. If not conclude that it can't be added, because it will break things?

Or, instead of using `Object.defineProperty`, you could use `Object.create(originalAction, { saga-props })`

**Comment by restrry** [comment]
`Object.create` resonates with redux action nature and it's official requirement to use plain object without inheritance https://github.com/reduxjs/redux/blob/master/src/createStore.js#L166
@Andarist we could use `WeakSet` or `WeakMap` and degrade to Array for old envs

**Comment by restrry** [comment]
@shinima

**Comment by shinima** [comment]
Could we wrap the actual channel payload into an object, and unwrap the object when we want to use payload?

 That means we change our `wrapSagaDispatch` as follows:

```diff
- export const wrapSagaDispatch = dispatch => action =>
-  dispatch(Object.defineProperty(action, SAGA_ACTION, { value: true }))

+ export const wrapSagaDispatch = dispatch => action => dispatch({ [SAGA_ACTION]: true, action })
```

stdChannel also needs changed:
```diff
export function stdChannel() {
  const chan = multicastChannel()
  const { put } = chan
  chan.put = input => {
    if (input[SAGA_ACTION]) {
-      put(input)
+     put(input.action)
      return
    }
-    asap(() => put(input))
+ // I'm not sure at the moment that `input.action` or `input` should be used here.
+    asap(() => put(input.action))
  }
  return chan
}
```

This approach seems to work and has less magic than  WeakSet/WeakMap.
How do you think about it ? @Andarist @restrry

**Comment by Andarist** [comment]
Problem with that approach is that whatis dispatched by `wrapSagaDispatch` is not only dispatched into the saga runtime but also to the outside world - other code has to operate on normal action objects

**Comment by Andarist** [comment]
Actually the easier task would be to just reimplement their scheduling technique here and see if tests are still passing.

**Comment by shinima** [comment]
@Andarist This is interesting, it would be great if we can remove all the `SAGA_ACTION` stuff. I'll take some time on digging it.

**Comment by Andarist** [comment]
I've started the research here - https://github.com/redux-saga/redux-saga/commit/7e56d81bedc9b058b043e1dcba40e3ac10b09892

With those changes we "only" have 2 failing tests, I've started to dig into why they are failing & comparing that to redux-observable behaviour, but can't yet tell much about it.

**Comment by Andarist** [comment]
I've tinkered with the scheduler quite a bit over the weekend and I have not found any way to make it work without this unfortunate mutations. Even WeakSet approach would just generate other issues. 

Having only a single report about this being a problem I'm forced to close this due to minor impact on the community & obvious lack of other solution. If anybody finds out how to make it work without this I would be more than happy to incorporate such a solution, but I strongly believe that this might be just impossible - we need to distinguish "external" and "internal" (aka put) dispatches to handle them slightly differently and without call stack introspection I have no idea how to solve it.

**Comment by topaxi** [comment]
I just ran into this issue today and subscribed to this issue, as a newcomer to this ecosystem, I debugged over an hour just to find the issue. I copied some action creator logic which froze actions on development environments. Not saying that the issue should be reopened, but just voicing my experience here as to why I think this should be fixed to prevent future newcomers some headaches.

**Comment by Andarist** [comment]
Thanks for the input @topaxi - it would probably be a good idea to detect this in dev mode & warn the users that if they want frozen actions then it would be better done in the middleware than in the action creators (accompanying README section would be nice too). I'll probably add this soon, before releasing final v1.

**Comment by Andarist** [comment]
I've created a PR with more helpful error for development mode - https://github.com/redux-saga/redux-saga/pull/1578

**Comment by cuzfrog** [comment]
If an action is immutable, it's safe to be reused. My example is that when one non-sealed action is reused, it's payload gets lost.
```
{
  type: "[game] set direction",
  payload: 1
}
// in redux-devtools, becomes:
{
  type: "[game] set direction"
}
```
Modifying actions is not a good idea. 
See also: https://github.com/Hotell/rex-tils/issues/21
