### ISSUE TITLE
Revamp testing docs

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1309]
There is an excellent article by @sh1989 with comparison of redux-saga testing approaches/libs:
http://blog.scottlogic.com/2018/01/16/evaluating-redux-saga-test-libraries.html

It would be super cool to have this text incorporated into our official docs.

**Comment by zgavin1** [comment]
Hi @sh1989 and @Andarist. I'm interested in helping improve the testing docs.

If you had anymore thoughts about this since January, let me know. I can't quite say yet whether concepts from Scott's text should just be more of an addendum or more integrated into the whole document. I'll dive in an see what is best for now.

**Comment by Andarist** [comment]
@zgavin1 Thanks for the contribution offer! We really appreciate it.

The only thing that comes to my mind beside what's already covered by the article is `effect` is that `effectMiddlewares` (available in v1-beta) can be used to intercept effects in tests to implement integration-like tests. Idea is that you can just create a real store, start a saga, intercept/resolve async effects with `effectMiddlewares` and assert on things like state updates etc.

**Comment by Andarist** [comment]
closed with #1433
