### ISSUE TITLE
Object.assign with redux action in other middleware copying symbols

### ISSUE THREAD

**Issue by jcarroll2007** [redux-saga/redux-saga#1348]
While writing some custom middleware for my react/redux app I came across an oddity with copying an action that contains a property that has been (I'm assuming) wrapped by redux-saga [here](https://github.com/redux-saga/redux-saga/blob/08428e288aa1a2d6e59bc6cb492739ef9b19c376/src/internal/utils.js#L182).

My middleware, for example purposes, essentially looks like this - 
```
export default function payloadWrapperMiddleware() {
  return store => next => defaultAction => {
    const action = Object.assign({}, defaultAction)
    action.payload = payloadWrapper(action.payload)
    return next(action)
  }
}
```

But when I console log the copied action and the default action the result is this:
![image](https://user-images.githubusercontent.com/8485105/36846193-b53f3016-1d27-11e8-8ea3-e3fc767246e5.png)

Any recommendations on how to properly copy the action so that the symbol defined by redux saga is not lost in object copying?

Thank you!

**Comment by Andarist** [comment]
Ideally we'll remove this extra symbol in the near future, but in the meantime it's intentionally not enumerable and `Object.assign` copies only own & enumerable properties.

As you know what the problem is you can just set it yourself conditionally on the resulting action, smth like
```js
import { SAGA_ACTION } from 'redux-saga/utils'

export default function payloadWrapperMiddleware() {
  return store => next => defaultAction => {
    const action = Object.assign({}, defaultAction)
    action.payload = payloadWrapper(action.payload)
    if (defaultAction[SAGA_ACTION]) {
      Object.defineProperty(action, SAGA_ACTION, { value: defaultAction[SAGA_ACTION] })
    }
    return next(action)
  }
}
```

Is there any reason why do u want to copy this object? Wouldnt it be easier to just mutate it? Why is it happening in the middleware? Shouldnt this be handled by action creator?

**Comment by jcarroll2007** [comment]
Thanks for the suggestion @Andarist. Is that symbol the only one that will be present on an action? I don't need to check for any other symbols?

 - Why not mutate it?
I could mutate it, but I'd prefer not too. I don't want to cause any side-effects.

- Why is this middleware?
Specifically, the middleware I'm using is [redux-normalizr-middleware](https://github.com/wbinnssmith/redux-normalizr-middleware/blob/master/index.js). The idea is that the action-creator will add some meta information that is used by this middleware to wrap the payload.

**Comment by Andarist** [comment]
> Thanks for the suggestion @Andarist. Is that symbol the only one that will be present on an action? I don't need to check for any other symbols?

It's the only one and even if we remove the need for it, we will probably have to rely on action identity and store it in some `Set` or something for a short period of time - in that case ur approach with copying the action instead of mutating it would actually hurt saga's scheduling (for some edge cases, but still), because you wouldn't be able to 'fix' it with copying a symbol

> I could mutate it, but I'd prefer not too. I don't want to cause any side-effects.

Sure, but avoiding side-effects for sake of avoiding side-effects is not good either. There are places where I'd avoid them at all costs and there are places where they just make our lives easier - this seems like the latter.

> Specifically, the middleware I'm using is redux-normalizr-middleware. The idea is that the action-creator will add some meta information that is used by this middleware to wrap the payload.

Looking into its code and it doesnt seem there is a reason to do this in the middleware, this would make it way easier to reason about if that normalizing could happen in action creator, seems more appropriate. I might be missing some use case, but at first glance this makes code more convoluted (action creation is becoming a 2 step process)

**Comment by jcarroll2007** [comment]
Thanks for all of the great points. I think I will just mutate the action. 

> Looking into its code and it doesnt seem there is a reason to do this in the middleware, this would make it way easier to reason about if that normalizing could happen in action creator, seems more appropriate. I might be missing some use case, but at first glance this makes code more convoluted (action creation is becoming a 2 step process)

Yeah, that's a good point.

Thanks for all of the help @Andarist.
