### ISSUE TITLE
Saga don't cancelled, but isCancelled() === true

### ISSUE THREAD

**Issue by borovik96** [redux-saga/redux-saga#1355]
I have this code:
[![Edit Saga](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5v7z51zyn4)

If you click cancel button and see to console, you will get 
![image](https://user-images.githubusercontent.com/9018702/37078158-245cd6ee-21ef-11e8-8f9a-f234460e3de4.png)

**Comment by Andarist** [comment]
Thanks for sharing a codesandbox it let me identify the issue way quicker than it would be possible without it.

The problem is that your "Is really canceled ?" is comming from NEXT "instance" of `handleWeb3Actions`. You can verify it by looking into the console, you will actually see this:
```
"Is really canceled ? " false // this is from the first instance that you are going to cancel in the future
web3 chanel
web3 chanel
web3 chanel
web3 chanel
// dispatch cancellation action
".isCancelled()" true // this is about first instance
"Is really canceled ? " false // this happens immediately in second instance, because it reaches the `finally` block
```

The reason is because `takeEvery` is non-blocking so you allow saga reaching your `finally` block prematurely. You should block your saga so the cancellation could work:
- either by joining a forked (from takeEvery) task
- writing takeEvery manually with while(true) loop - it would block your saga in the loop

**Comment by borovik96** [comment]
Thank you a lot, it works with manualy looping
