### ISSUE TITLE
Typescript 2.7, Spread Operator, Redux-Saga `call` Signature

### ISSUE THREAD

**Issue by cwmacdon** [redux-saga/redux-saga#1371]
We have a convenience function that wraps `race` with a given `timeout`. The code compiled with Typescript 2.6, but now no longer works. I've removed some extraneous types and made the code as short as possible for this example.

```typescript
function * callWithTimeout(timeout: number, fn: any, ...args: any[]) {
    const { results, timedOut } = yield race({
        results: call(fn, ...args),
        timedOut: call(delay, timeout)
    });

    return timedOut ? { timedOut } : { results };
}
```
The error from the compiler is: 
![image](https://user-images.githubusercontent.com/957907/37745137-93a6c86a-2d49-11e8-971a-40f59cfb9b87.png)

**Comment by cwmacdon** [comment]
I should note that this problem exists in `redux-saga` in `0.16.0` as well as `1.0.0-beta.0`

**Comment by Andarist** [comment]
@aikoven could you take a look if you have some spare time? Sorry for pinging you for those cases over and over again

**Comment by aikoven** [comment]
@cwmacdon Unfortunately, for now, there's no way to handle this in a type-safe manner. We could add a variadic signature for `call`, something like:
```ts
function call<T>(fn: (...args: T[]) => any, ...args: T[]): CallEffect;
```
But if we did, then this code would compile without errors:
```ts
function someFunc(foo: string) {...}

yield call(someFunc);  // `foo` argument is missing
```
because TypeScript doesn't allow to control the number of arguments in a variadic function.

That's why current typings don't include fully variadic versions for effects like `call`, `fork` etc. That's a tradeoff to provide type safety for the most common usage, where arguments are static.

For the dynamic case, like yours, I'd go with:
```ts
(call as any)(fn, ...args),
```

@Andarist Don't apologize, I wouldn't expect you to take the burden of maintaining typings that you don't even use 😀. Please feel free to ping me anytime.

**Comment by cwmacdon** [comment]
@aikoven OK cool thanks for the quick response. I had taken a look at the history of the `effects.d.ts` file and noticed there had been some changes around the types and arity. Wasn't sure if there was any new stuff that the TS team had maybe introduced that could help, if they were now failing in this case.

I'll do the workaround for now. I'm cool with closing this.

Cheers!
