### ISSUE TITLE
when will redux-saga migrate to async/await?

### ISSUE THREAD

**Issue by anymost** [redux-saga/redux-saga#1373]
As the title showed, I want to know when redux-saga will migrate to async/await, The generator function is too complicated to use.

**Comment by Andarist** [comment]
No.

From the user perspective it is no different than async/await - effects are yielded and u can think of that as they would be "awaited". 

From the library's (redux-saga) point of view async/await is to generators like a younger, dummy brother 😉 You can do much, much more with generators than with async/await.

Please also read [this comment](https://github.com/redux-saga/redux-saga/issues/987#issuecomment-301039792)

**Comment by hoodwink73** [comment]
Hey @Andarist 

Thanks for your efforts in Redux Saga.

Will you be open to adding a small section in the docs detailing why redux-saga uses generators over async/await and a disclaimer that we will not be using async/await?

There is a similar question raised in [StackOverflow](https://stackoverflow.com/questions/43443620/redux-saga-async-await-pattern) too.

**Comment by Andarist** [comment]
I'm totally open for adding it, just not for adding it myself. Would you like to compile those 3 comments into a single short-ish section of the README?

**Comment by hoodwink73** [comment]
Absolutely. Will raise a PR.

**Comment by Andarist** [comment]
Cool, thank you very much! 👍

**Comment by sincerekamal** [comment]
@Andarist Interested and eager to know what much more things `redux-saga` is doing with `generators` which is tough or impossible with `async/await`

**Comment by Andarist** [comment]
@sincerekamal cancellation for starters - u cant cancel promises (which are ultimately created when calling async functions), but u can stop iterating through an iterator (u can even call its `return` method)

**Comment by antialias** [comment]
> u can even call its return method

`return` is a statement.

**Comment by alankar-anand** [comment]
I have used async await inside Redux saga. Here's the question on [stackoverflow](https://stackoverflow.com/q/51951839/6763126). Both can co-exist if someone wants to use it that way.

**Comment by Andarist** [comment]
@antialias 

It's also iterator's method 😉 
```js
function *saga() {}
var it = saga()
it.return()
```

**Comment by antialias** [comment]
Cool! I'm apparently still learning about this stuff. Thanks @Andarist

**Comment by ceefour** [comment]
@Andarist I'm sorry to use this as a question, but I'd like to know how to do "await" with `redux-saga` ?

What I mean is, by `dispatch()`-ing an action, `redux-saga` will run it in background.

The problem is, I'd like the button (or whatever is the UI), to "await" the saga.

In essence:

```typescript
try {
  await dispatchSomething();
  console.info("Yay it's done");
} catch (err) {
  console.error("Saga gave me error:", err);
}
```

Currently I'm doing something like this instead:

```typescript
return new Promise((resolve, reject) => {
  dispatchSomething(resolve, reject);
}).then(res => console.info("Yay it's done"))
.catch(err => console.error("Saga gave me error:", err));
```

**and** the saga must call the given `resolve` / `reject` from the action, which seems to be weird...

**Comment by shellscape** [comment]
@Andarist I just had to jump in here and poke you on this 😄  while iterators seem to have a use case here, the developer experience could be improved by leveraging async/await (which I dare say is much more common these days) along side for those who don't need the advanced capabilities of generators. I ended up here because one of our devs asked me to review a PR, and while I'm more of a backend monkey these days, I'd never seen redux-saga in the wild. It totally threw me off to see generators still around! I hadn't seen them since the pre-2.0 days of Koa!

**Comment by Andarist** [comment]
async/await is very much support - all the things you have to do is to:
```
yield call(asyncFn)
// or
yield asyncFn()
```
However, the first one is preferred.

I understand the generators are not as popular of a choice usually but they actually fit perfectly here. I also fail to see what using async/await would actually solve here - after all, async/await "just works" with Redux (u'd only need a very thin middleware). async/await pretty much nullifies everything that redux-saga offers so it just can't just be used as a primary user-facing API - the redux-saga would just not be redux-saga anymore with that.

There is, of course, a point in being able to call into async functions - but as mentioned, that's already covered.
