### ISSUE TITLE
incomplete errors in Firefox and Safari

### ISSUE THREAD

**Issue by nchevobbe** [redux-saga/redux-saga#1376]
Hello, Firefox DevTools Webconsole maintainer here. 
We got a bug report about incomplete errors in Firefox for an application using redux-saga (See https://discourse.mozilla.org/t/variable-dont-reported-as-undefined-how-to-replicate-and-screens/26965).

Here's the test case run in Chrome, FF and Safari

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/578107/37889897-be2b1a5e-30ce-11e8-8375-5fc8a7345dd6.png">

As you can see, both FF and Safari are missing the ` TypeError: Cannot read property 'b' of undefined` message (the bug report is on 0.14.0, but I reproduce it on 0.16.0).
It looks like the library was using `Error.prototype.stack` to log errors but this doesn't seem to be the case anymore (I can't find the faulty code in the repo now, so maybe it will be fixed in next release ?)

**Comment by Andarist** [comment]
> It looks like the library was using Error.prototype.stack to log errors but this doesn't seem to be the case anymore (I can't find the faulty code in the repo now, so maybe it will be fixed in next release ?)

For a brief moment I've even tried to normalize those, but IMHO it isn't something sustainable in a long run - so I've removed this thing entirely. 

The plan now is to log original error but log additionally a prepared "saga trace" to improve debuggability (which can be enhanced with file names & line numbers with a [babel plugin](https://github.com/redux-saga/redux-saga/tree/master/packages/babel-plugin-redux-saga) that we are working on). 

I don't expect to be an issue with future redux-saga@1 (beta.0 already got published some time ago) and because of limited resources we do not plan to release anymore in the 0.x line.

**Comment by nchevobbe** [comment]
Thanks for your answer @Andarist

**Comment by pizza-r0b** [comment]
@Andarist is there a branch for the 0.x line ?

**Comment by Andarist** [comment]
I've created it now - https://github.com/redux-saga/redux-saga/tree/0.x

**Comment by Andarist** [comment]
The release of v1 is really coming soon-ish (hope to get it out this month) - so closing this issue in favour of using v1 which will have better errors by default
