### ISSUE TITLE
Seperate JS thread for React-Native

### ISSUE THREAD

**Issue by zsajjad** [redux-saga/redux-saga#1422]
Thanks for the amazing work!

This issue is just discussion!

I am using saga for developing a react native, I love the idea of keeping async tasks out of main app thread but going a step further it shouldn't be just a mental-model rather it should be a proper separate thread while working on large scale performance oriented apps. I don't if there is any such package available or not but i think its achievable using [react-native-threads](https://github.com/joltup/react-native-threads) for react-native specially.

**Comment by Andarist** [comment]
You could achieve it by putting your whole redux store in a worker/thread, but that requires some additional setup. I don't think putting only redux-saga's middleware in a thread is a good idea, because it has to have access to your store (getState and dispatch methods) so you'd have to tie your integration yourself to achieve this.

**Comment by vikasraj789** [comment]
Try [stockroom](https://www.npmjs.com/package/stockroom). I guess it is basically for web.

**Comment by zsajjad** [comment]
@Andarist Do you anticipate this could help in boosting the performance especially when you're working with React Native?

**Comment by Andarist** [comment]
Not rly, saga should be "fast enough". Experimentation around this would be cool, but would have to be done outside of this project.
