### ISSUE TITLE
Cannot capture error from reducer

### ISSUE THREAD

**Issue by ovaldi** [redux-saga/redux-saga#1510]
Sometimes, the error might throw from reducer, but I see the errors get logged to the [console.error ](https://github.com/redux-saga/redux-saga/blob/v0.16.0/src/internal/utils.js#L153)(which is not throw up error to global), so the monitoring service(such as [Sentry](https://docs.sentry.io/clients/javascript/integrations/react/)) cannot capture the exception, is there a way to do this?

for example: 
   
```
function* mySaga () {
     try {
        const entity = yield call(api.fetchXX);
        yield put({type: 'FETCH_SUCCESS', payload: entity });
     } catch (error) {
       Toast.fail(error.message);
     }
}

function myReducer (state, action) {
    switch (action.type) {
       case: 'FETCH_SUCCESS':
          return action.payload.nickname; // Error: Cannot read property 'nickname' of null
    }
}
```

Hi @Andarist could you help me?

**Comment by shinima** [comment]
You can use [createSagaMiddleware#options.onError](https://redux-saga.js.org/docs/api/#createsagamiddlewareoptions) as an error handler for saga-middleware.

**Comment by shinima** [comment]
I've made a test on codesandbox:   https://codesandbox.io/s/m79rn28z9y?expanddevtools=1&view=editor

Have a look.

**Comment by ovaldi** [comment]
@shinima Oh, I see it works on redux-saga@v1.0.0-beta.1, cool!
BUT, it does not work on v0.16.0 :(

**Comment by shinima** [comment]
@ovaldi  This seems like a bug of v0.16.0, but I'm not sure about it since it is an old version for me.

One workaround for v0.16.0 is [using `put.resolve` instead of `put`](https://codesandbox.io/s/4xkq21kw0x) when the reducer may throw an exception. On the other hand, reducers are supposed to be pure functions and it is not a good idea to have reducers throw exceptions which makes code hard to test.

**Comment by ovaldi** [comment]
Yeah, it might be a bug of v0.16.0, anyway, thank you @shinima 
Looking forward to v1.0.0 released asap!

**Comment by restrry** [comment]
JFYI that behaviour was by design until v1. that's one of breaking changes for v1 https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0-beta.0
> errors thrown during put execution are no longer caught and swallowed, you need to catch them manually

discussion is here https://github.com/redux-saga/redux-saga/issues/632

**Comment by Andarist** [comment]
This one was a mistake of some 0.1x version - errors should always crash ur sagas if they stay uncaught. It's fixed in v1 line (even if it's beta, do not be afraid of using it - it's not a rewrite, just mild evolution of the codebase, it's still tested and all. Just pin your version in package.json)

**Comment by ovaldi** [comment]
Got it, thank you @restrry @Andarist  :)
