### ISSUE TITLE
rootSagas what is the best way

### ISSUE THREAD

**Issue by tastafur** [redux-saga/redux-saga#1512]
### rootSagas use all effect simple or use all + fork, which is the best option?

thanks for the help, I've been reading and reading and it's not clear to me

**Comment by zgavin1** [comment]
Hey @tastafur I just actually wrote some docs to help explain this here: https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/RootSaga.md. _But_ I realized that I never added a link to  this page to the Table of Contents. I will make a PR for that asap.

**Comment by Andarist** [comment]
Need to publish them manually for now, I'm not sure though if current docs are not mix of v0.16 and v1. We are heading towards making v1 stable, so I would prefer holding for a little bit longer with deploying the docs.

**Comment by tastafur** [comment]
@zgavin1 I have read your documentation and what I understand in this way 
```javascript
export default function* rootSaga() {
  yield all([
    helloSaga(),
    watchIncrementAsync()
  ])
}
```
you initiate non-blocking parallel effects but in this way also
```javascript
export default function* root() {
  yield all([
    fork(saga1),
    fork(saga2),
    fork(saga3)
  ]);
}
```
I do not understand the difference between these two ways of implementing rootSagas

**Comment by shinima** [comment]
I'm thinking that `yield all([ fork(saga1), fork(saga2), fork(saga3) ])` is not a good pattern to implement sagas.  It may **mislead** people to think that the fork-effects are managed by the call-effect, and call-effect will be resolved after all the forked tasks completes. 
But actually, the fork-effects are always managed by the current task through the underlying forkQueue. Call-effect will be resolved immediately since all fork-effects are non-blocking. Errors from the forked tasks bubble to the current task rather than to the call-effect.

So it is better to design root saga as follows:

```diff
- yield all([ fork(saga1), fork(saga2) ])

// using multiple fork-effects
+ yield fork(saga1)
+ yield fork(saga2)

// or ...
+ yield all([ call(saga1), call(saga2)])
```

By the way, fork-effects in race-effect is  most likely a bug since fork-effects are non-blocking and they will always win the race immediately.

``` javascript
// DO NOT DO THIS. The fork-effect always win the race immediately.
yield race([
  fork(saga1), 
  take('ACTION-1'),
  somePromise,
])
```

The rule of thumb is that use fork-effect directly in your saga, do not nest it in other effects.

**Comment by zgavin1** [comment]
@tastafur: @shinima has it. That would be very help to include that information in the docs page, as I totally agree with you. I was halfway through commenting here that there probably should be an example of a root saga that yields just an array of fork effects, rather than passing an array of them to a call effect. You articulated it it better than I could.
