### ISSUE TITLE
Why there is no mention in docs about sagas purity?

### ISSUE THREAD

**Issue by DimatiBart** [redux-saga/redux-saga#1520]
Hey folks, as far as I understand, the common paradigm of writing sagas is to make them pure - which  could be seen in the official docs examples and articles. But there is no explicit explanation that sagas should be pure and why it's necessary. As a result, I found multiple examples of makings some side effects (e.g. changing browser history) in production code sagas. 

So, my questions are:
- Should sagas always be pure?
- If yes/not, could it be mentioned in docs, so it won't be confusing for other developers.

Cheers

**Comment by anthonychung14** [comment]
When you say "pure", I'm interpreting that as "no side-effects". This is puzzling to me.

Redux-Saga is a library for managing and creating side-effects (like async processes, timeouts, etc.). Even though it adopts the "side-effects as data" paradigm, I don't think they need to necessarily be "pure" in the Redux sense (like how a reducer always outputs a new state tree).

So no. Sagas don't need to be pure, which is why it's not mentioned in the docs.
