### ISSUE TITLE
Bug: Saga effects are not executed server side

### ISSUE THREAD

**Issue by metsavaht** [redux-saga/redux-saga#1562]
#### Description of the bug/issue

Saga effects are not called server side. `task.isRunning()` returns false and toPromise resolves immediately.

#### Steps to reproduce the bug/issue

1. Use `redux-saga` in server environment
2. Run saga with `sagaMiddleware.run(testSaga)`
3. Called saga resolves immediately 

#### Example
private repo, can provide example repo if required. Can do that tomorrow.

```
function* testSaga() { 
  const result = yield take('TEST');
  console.log(result);
}
```

### Actual results
```
{"TAKE":{"pattern":"TEST"}}
```

### The Expected results
Saga would block request forever.

### Environment information

- redux-saga v1.0.0-beta.1
- Babel and WP4
- Koa server framework
- Server side renderer hot reloading

**Comment by shinima** [comment]
Saga use an internal Symbol `IO` to mark an object as effect. I think this issue is caused by incorrect setup of redux-saga so that there are two different symbols —— the saga middleware uses different symbol from `take` so it does not recognize the take-effects.

Is there multiple copies of redux-saga installed (maybe caused by symbolic link of directory)? Or is it the reason that hot-reload runs redux-saga multiple times and create multiple `IO` symbols?

**Comment by metsavaht** [comment]
Single copy is installed.
redux-saga is started in request which calls function to creates store with the middleware.
Server renderer is compiled with Webpack and everything from node modules is marked as externals.
When running on client side, sagas run correctly.

Same code worked with `v0.16.0` which probably did not use Symbol's.

Will investigate further.

**Comment by shinima** [comment]
Really strange behaviors. The take-effects are handled [here](https://github.com/redux-saga/redux-saga/blob/v1.0.0-beta.1/packages/core/src/internal/proc.js#L385), would you mind add a breakpoint and see what's going on?

> private repo, can provide example repo if required.

an example would be helpful.

**Comment by metsavaht** [comment]
I'll try to create an example but when it was used as `commonjs` external module, effects where not detected with debugger.

After excluding `redux-saga` from externals sagas where running correctly.

**Comment by Andarist** [comment]
Without providing sufficient information (ideally a repository with the issue reproduced) we are not able to help you any further, if you manage to prepare one we will reopen the thread.

**Comment by ronen** [comment]
In case anyone is still reading this, I came across a similar problem using v1.0.0-beta.2.  This has been fixed by #1584 (replaced symbols with strings), but since that hasn't been released yet, those using v1.0.0-beta.2 may still encounter this problem.   

Details: In my environment (electron-webpack, babel, ES6) some code paths were loading `@redux-saga/symbols/dist/symbols.cjs.js` and others were loading `node_modules/@redux-saga/symbols/dist/symbols.esm.js`, so the symbols were created twice.  This meant that different parts of the code would use different values for the symbols. In particular, internally, `makeEffect` would create an effect with `effect[IO]` being `true`, but when `runEffect` tested `effect[IO]` it would evaluate as `undefined`, and the effect would not run.

My workaround is to use [patch-package](https://www.npmjs.com/package/patch-package) to replicate 4ad8ecdd38b0e77d583d6f591928e308b801c862 until the next release.  I.e. I edited both `node_modules/@redux-saga/symbols/dist/symbols.cjs.js` and `node_modules/@redux-saga/symbols/dist/symbols.esm.js` to and replaced the definition of `createSymbol` accordingly.

**Comment by Andarist** [comment]
@ronen thanks for the report, going to cut a new beta release today so u dont have to hack around this issue

**Comment by ronen** [comment]
@Andarist great thanks!

**Comment by Andarist** [comment]
Published
