### ISSUE TITLE
Scheduler can get into bad state with takeEvery or takeLatest inside a while(true)

### ISSUE THREAD

**Issue by ryanashcraft** [redux-saga/redux-saga#1624]
### Context

We had reports that our app was not behaving correctly in the Edge browser on Windows. I spent a long time trying to debug why our saga code was behaving differently in Edge versus other browsers. The immediate symptom was that none of our `take` effects were getting called. To make matters worse, the issue would not reproduce when the Developer Tools were open.

I debugged the redux-saga scheduler and observed that whenever the issue would appear, the semaphore value would get stuck at a positive value: https://github.com/redux-saga/redux-saga/blob/2aecdb310db8760ddd2c2513bf1cce7174c289d9/packages/core/src/internal/scheduler.js#L9

I could manually invoke `flush` and the takes started working correctly.

After ruling out issues in the asap/scheduler code, I noticed that the suspend and flush were being used in the `runForkEffect`: https://github.com/redux-saga/redux-saga/blob/2aecdb310db8760ddd2c2513bf1cce7174c289d9/packages/core/src/internal/proc.js#L512-L530

I added a `setTimeout` with a 5-second duration before the `suspend` call and a `clearTimeout` before the `flush`. Turns out that the intermediate code was taking an indeterminate (infinite?) amount of time. This explained why the semaphore value was not ever decreasing back to 0.

After many attempts to figure out why this was happening, on one test I triggered a stack overflow with an interesting stack trace. The stack included code that was yielding a `takeEvery` effect inside a while loop. I immediately noticed this was bad and boom – Edge now behaved correctly.

I did not do any more investigation to understand in more detail why redux-saga behaves this way and why that behavior varies depending on the browser.

### Desired outcome

It would be great if redux-saga could somehow avoid this issue altogether or throw an error with useful debugging information.

### Steps to reproduce

1. Fork multiple sagas. Have one of your sagas contain a `takeEvery` inside a `while (true)` loop (I realize you'd never intentionally want to do this…). Have another saga `take` actions.
2. Run the code on different browsers (Chrome, Edge). Notice different behaviors where on some browsers, the second saga's `take` effect won't behave correctly (if the `take` uses a callback for the first param, its callback is never called).

#### Example

https://codesandbox.io/s/zn2xl52zx3

A modified fork of a codesandbox example I found.

Correct behavior: click on the "one" button and next to the "ONE:" label you'll see "a0" and half-a-second later you'll see "a0" next to the "TWO:" label.

Incorrect behavior: click on the "one" button and next to the "ONE:" label you'll see "a0" and half-a-second later nothing happens.

### Actual results

Depending on the browser, things might appear to work fine. On my computer, the `take` effects work in Chrome (Mac OS, Chrome 69), but on other Windows computers they don't work in Edge (41.16229, EdgeHTML 16.16299).

### Environment information
- redux-saga version: 1.0.0-beta-2 and 0.16

### Thank you

Thanks to all the contributors for maintaining redux-saga!

**Comment by Andarist** [comment]
Thanks for the detailed explanation! I really enjoy when one takes time to describe their issue thoroughly. 

That being said this sandbox is not an exact reproduction of your cause - codesandbox uses a custom babel plugin which wraps potentially infinite loops (such as `while(true)`) with a "stack frame counter" and throw the error if they detect such potential issue. It's implemented to avoid freezing the browser.

When you refresh your sandbox you might see that it's not responsive for a while - until the injected code throws because of the stack overflow.

The other question is - why this error is not visible and why it doesnt seem to be caught by redux-saga runtime? I dont have an answer for that now, but I definitely need to dig into this.

The only thing that comes to my mind why this might behave differently across browsers is that each browser has different stack space dedicated for your JS, basically each engine might allow for various depths of recursion. 

This still doesn't explain the issue in full - but maybe somehow stack limit exceeded errors are somehow handled differently and causing weird errors.

In any case takeEvery/takeLatest/etc in while loop is not a good idea and has zero chance of working properly in any environment. If it works anyhow in Chrome I'm pretty confident that saga runtime is in some inconsistent state because of this and might cause bugs in unpredictable ways.

**Comment by restrry** [comment]
closed to have all related discussions in one place https://github.com/redux-saga/redux-saga/issues/1624

**Comment by hallvar** [comment]
The referenced issue of where to have related discussions is this one. What is the correct issue number?

**Comment by Andarist** [comment]
#1592
