### ISSUE TITLE
Saga running at increasing multiples 

### ISSUE THREAD

**Issue by oamunoz** [redux-saga/redux-saga#1644]
Hello,
I'm new to sagas and have been working on a project using react-redux, connected-react-router, and redux-saga (no react-redux-saga-boilerplate).

The issue I'm facing seems most related to this post: [success actions runs multiple times](https://stackoverflow.com/questions/44409189/success-actions-runs-multiple-times). In our case, a saga will run once the first time we dispatch it's watched action. However, upon executing a route change, The next saga to run will be executed 7 times after a single action dispatch. With each dispatch the corresponding saga will be executed an increased amount, eventually slowing the app to a crawl. 

Now, in the answer provided at the post above, they suggest cancelling sagas upon LOCATION_CHANGE. Can anyone expand on if this would be true and why?  How does one determine the need to cancel a saga? In the updatePreviewSaga below, wouldn't it complete after `yield put(actions.previewUpdateHubRxCompleted(preview));` ?

```javascript
export  const previewSagas = [
    takeEvery(actions.previewUpdateHubRx, watchUpdatePreviewSaga),
    takeEvery(actions.setPreviewRx, watchSetPreviewSaga),
    takeEvery(actions.previewDemoUpdateRx, watchUpdateDemoPreviewSaga)
]

function* updatePreviewSaga(action) {
    try {
        console.log('update preview initiated');
        const preview = yield (PreviewService.updateHub(action.payload));
        preview.isLoaded = true;
        yield put(actions.previewUpdateHubRxCompleted(preview));
    } catch (error) {
        yield put(actions.previewUpdateHubRxFailed())
    }
}

function* watchUpdatePreviewSaga() {
    yield takeEvery(types.PREVIEW_UPDATE, updatePreviewSaga)
}
```

[previewSagas.txt](https://github.com/redux-saga/redux-saga/files/2504657/previewSagas.txt)

**Comment by shinima** [comment]
I think you may miss something but I could not say it clearly. I'll show you how `takeEvery` is implemented (so you can know the behavior of `takeEvery`) and then use a simpilied example to show how to code in such `onPageChange` scenarios.

`takeEvery` is implemented as following:

```javascript
export function takeEvery(pattern, worker, ...args) {
  return fork(function* watcher() {
    while (true) {
      const action = yield take(pattern)
      yield fork(worker, ...args, action)
    }
  })
}
```

Yielding `takeEvery(...)` will *fork* a watcher that has a while-true loop inside it, so after yielding it, every FOO action will have a worker to handle it. The watcher is a long-running task that never completes (because of the while-true loop). To stop the watcher, you need to cancel it manually at proper time (for example, when user navigates to another page).

And below is a simplified example that shows how to cancel such watchers when user navigates to another page.

```javascript
function root*() {
  // assume that every time user navigates to a new page, a PAGE_CHANGE action will be dispatched
  yield takeEvery('PAGE_CHANGE', pageChange)
}

// This is **wrong** implementation of `pageChange`
// every time the page changes, new watchers are added, but old watchers do not get removed
function pageChange1*({ nextPage }) {
  if (nextPage === 'page-a') {
    // user navigates to page-a, so we need to add watchers for actions dispatched from page-a
    yield takeEvery('FOO-IN-PAGE-A', handleFooInPageA)
    yield takeEvery('BAR-IN-PAGE-A', handleBarInPageA)
  } else if (nextPage === 'page-b') {
    yield takeEvery('BUZZ-IN-PAGE-B', handleBuzzInPageB)
  }
}

// This is correct (though ugly) implementation of `pageChange`
let tasks = [] // using a global variable to save the old tasks
function pageChane2*({ nextPage }) {
  // cancel all old tasks
  for (const task of tasks) {
    yield cancel(task)
  }
  tasks = []
  if (nextPage === 'page-a') {
    tasks.push(yield takeEvery('FOO-IN-PAGE-A', handleFooInPageA))
    tasks.push(yield takeEvery('BAR-IN-PAGE-A', handleBarInPageA))
  } else {
    tasks.push(yield takeEvery('BUZZ-IN-PAGE-B', handleBuzzInPageB))
  }
}
```

Manually saving and then cancelling the tasks is cumbersome, we can utilize the `takeLatest` helper to get much more concise implementation as follows:

```javascript
function root2*() {
  yield takeLatest('PAGE_CAHNGE', pageChange1)
}

function pageChange1*({ nextPage }) {
  if (nextPage === 'page-a') {
    // user navigates to page-a, so we need to add watchers for actions dispatched from page-a
    yield takeEvery('FOO-IN-PAGE-A', handleFooInPageA)
    yield takeEvery('BAR-IN-PAGE-A', handleBarInPageA)
  } else if (nextPage === 'page-b') {
    yield takeEvery('BUZZ-IN-PAGE-B', handleBuzzInPageB)
  }
}
```

When another PAGE_CHANGE action dispatches, the `takeLatest` helper will cancel the last `pageChange1` watcher, and since [the cancellation propagates downward](https://redux-saga.js.org/docs/advanced/TaskCancellation.html) all sub-watchers (for example, `handleFooInPageA` and `handleBarInPageA` will get cancelled), then the `takeLatest` will start a watcher using the newer action.

**Comment by oamunoz** [comment]
Shinima, thank you for expanding on how takeEvery and it's cancellation work. After I read your post I went back to re-read my code and saw that I was basically dispatching watcher tasks rather than the actual sagas that were supposed to be responding to specific actions. It makes sense why I was getting multiple sagas responding to the single action. 

Thank you!

By the way, in dealing with the issue above I came up on an article you helped write [RoogSaga](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/RootSaga.md). Will you guys be moving that to your [docs](https://redux-saga.js.org/docs/advanced/), because that would have been super useful when I was creating the root saga for the first time?

**Comment by shinima** [comment]
redux-saga.js.org reflects the latest version of redux-saga (currently it is v0.16.x, v1.0 is just in beta now), so the content will remain untouched before redux-saga v1 comes out. When we publish redux-saga v1.0, we will update the documentation site.

**Comment by shinima** [comment]
Closing it.  If you have further questions, just re-open it.
