### ISSUE TITLE
Is `delay` intended to be blocking?

### ISSUE THREAD

**Issue by nwpray** [redux-saga/redux-saga#1741]
### Description
Using the following example for context:
```
function* waitFor(channel, desiredActionTypes){
  let result;
  do {
    result = yield take(channel);
  } while(desiredActionTypes.indexOf(result.type) < 0);
  return result;
}

function* someSaga() {
  const channel = someChannelFactory();
  
  const { response } = yield race({
    response: waitFor(channel, ['DESIRED_ACTION_TYPE']),
    timeout: delay(5000);
  });

  console.log('wanted this to print before exit');

  return response;
}

function* anotherSaga() {
  const responseFromSomeSaga = yield call(someSaga);
  
  console.log(responseFromSomeSaga);
}
```

So, I had hoped that someSaga wouldn't return until the race was complete. But because delay isn't blocking? 'wanted this to print before exit' will never print. I ended up making a custom blockingDelay that wraps setTimeout. So, I was just curious if that was intended? If so, can we get a bit more documentation about `delay` saying that it is non blocking? Maybe also a bit more documentation about `race` talking about conditions it would be blocking and conditions it wouldn't be blocking in? It may also be nice to have a blocking flavor of `delay`. You could even pass in an optional second boolean which determines if it blocks or not.

**Comment by shinima** [comment]
`delay` is blocking, for example, the generator will suspend at `yeild delay(1000)` for 1 second. You can view the source code of `delay` [here](https://github.com/redux-saga/redux-saga/blob/b0b3d51d62/packages/delay-p/src/index.js), and I think it should be very much like how you define `blockingDelay`.

IMHO, `console.log('wanted this to print before exit');` not being executed is unrelated to `delay` or `race`. It seems that `someSaga` got cancelled before printing `'wanted this to print before exit'`, this may be caused by an exception while executing `waitFor(channel, ['DESIRED_ACTION_TYPE'])`, or caused by cancellation from the `anotherSaga`.

**Comment by nwpray** [comment]
Your totally right @shinima, thank you! I should have been a bit more thorough. Here is a [sandbox](https://codesandbox.io/s/24j0jlor4y) if anyone is interested in seeing it work in action.
