### ISSUE TITLE
Can a dispatched action finish before take(action) is called

### ISSUE THREAD

**Issue by tobloef** [redux-saga/redux-saga#1761]
Let's say that I have something like the following code in my saga:

```javascript
...
yield put(SomeAction);
yield take(SomeAction);
...
```

Can the dispatched action finish before `take` is called, causing the code to stall until the action is dispatched again, or will this always work as expected? If that doesn't work, how else can I dispatch an event and then wait for it to complete?

Thanks!

**Comment by MichelSimonot** [comment]
I have a similar scenario, except my event is asynchronous, so I have a separate action to signify that the side-effect has finished (which makes my scenario simpler to handle than yours).

``` javascript
// Another saga does something async with 'DO_THING', then puts 'DO_THING_FINISH'.
yield put('DO_THING')
const result = yield take('DO_THING_FINISH')
```

In the past, I've had to awkwardly use an action channel to make sure I catch an action. 

``` javascript
// Setup an action channel to queue the "finish" signal before dispatching the action.
const channel = yield actionChannel('DO_THING_FINISH')
yield put('DO_THING')

const result = yield take(channel)
// The channel was just for the single-use, so clean it up.
channel.close()
```
And this was because of timing issues (`DO_THING_FINISH` could be dispatched before `DO_THING` finishes in non-async scenarios). I don't do this anymore, but that's more to do with how my other saga handling `DO_THING` works.

**Comment by tobloef** [comment]
My problem is actually very similar to yours, I just simplified for the question.

**Comment by MichelSimonot** [comment]
This discussion also seems related: https://github.com/redux-saga/redux-saga/issues/1699

**Comment by neurosnap** [comment]
In general my recommendation would be to have a `COMPLETE` action that gets called when `SomeAction` is complete.  Also if `SomeAction` has its own saga that is doing the processing, I'll often times call the saga itself instead of dispatching an action.

ex:

```js
yield call(SomeActionSaga);
// ... everything after this gets called after SomeActionSaga is done
```

Closing now due to inactivity but please feel free to reply and I'll reopen for further discussion.
