### ISSUE TITLE
takeLatest (and friends) does not work with multicast channels

### ISSUE THREAD

**Issue by Alxandr** [redux-saga/redux-saga#1796]
### Steps to reproduce
```js
const channel = multicastChannel();
yield takeLatest(channel, worker); // attempt 1
yield takeLatest(channel, '*', worker); //  attempt 2
yield put(channel, {type: 'foo'});
```

#### Description of the bug/issue
The `takeLatest` helper does not allow passing in a matcher when used with multicast channels, which crashes when the multicast channel tries to do `taker[@@match](action)`, because the match function is not set.

### Environment information
redux-saga version 1.0.1

**Comment by Andarist** [comment]
That's true I guess - but not sure what we can do about it right now. This would be a breaking change and I would like to avoid those if we can. Implementing support for this would also cause some not so pretty code included in those helpers as this is a special case.

The best what we could offer in terms of APIs would be:
```js
yield takeLatest([channel, '*'], worker);
```
And that's only because channel is not a valid "pattern" so we could check first argument against being an array and later agains being an array of patterns or this channel + matcher tuple

**Comment by Alxandr** [comment]
Yeah, I was thinking something like that. For now I just made a `takeLatestMulticast`, but I would like to not have subtle differences that I don't know about between my implementation and the base one 😛 .

**Comment by Andarist** [comment]
If you are willing to implement this feature - we would merge this in, but Im afraid we might not have time resources to do this ourselves at the moment.

**Comment by Alxandr** [comment]
Well. It would likely only be a few lines of change; so I can probably look at it later today if I remember 🙂

**Comment by neurosnap** [comment]
Closing for now due to inactivity.  I realize the resolution is a PR but since it’s been years since the last post I’m going to close for now.  Please feel free to reply and I can reopen for further discussion.

**Comment by simonbuchan** [comment]
For giving this better google-juice I believe I'm hitting this with the error `taker[MATCH] is not a function` ?

It's rather unfortunate that the types are perfectly happy with passing a `MulticastChannel<T>` to a `TakeableChannel<T>`, but I don't know if there's much that can be done there without some pretty ugly hacks.
