### ISSUE TITLE
Something not clear with runSaga and tests

### ISSUE THREAD

**Issue by mean2me** [redux-saga/redux-saga#1834]
### Description
Hello guys,
I've been trying to understand but couldn't find anything useful to me about the following problem.

Following the documentation, I tried to test my saga using runSaga but seems like it's hanging waiting for **take** to resolve.

Here is my code sandbox: https://codesandbox.io/embed/rl9ykvlvvp

Is there anything I'm missing?

**Comment by zhaoyingdu** [comment]
the part your code is missing is that, there is no code dispatching actions to your already running saga. So it is blocked on take, and is not a bug but expected behaviour.

the error rooted from this difference between your code and the correspondence in the doc:
```javascript
// root saga from the doc
function* callApi(url) {
  const someValue = yield select(somethingFromState);
  try {
    const result = yield call(myApi, url, someValue);
    yield put(success(result.json()));
    return result.status;
  } catch (e) {
    yield put(error(e));
    return -1;
  }
}

// root saga from your test
function* saga(action) {
  while (true) {
    const payload = yield take(action);
    yield fork(handler, payload);
  }
}
```

the saga from the doc is testable with the other part of the code is that, upon calling runSaga(), the doc's   root saga can run from start to end by it self (it does not depend on an action dispatched to it for it to proceed, or in other work, it is not `taking` any actions at all, at least for it to run, it should not `take` any action that won't be dispatched(or put) by the saga itself). 

I have edited a bit of your code, (edited)[https://codesandbox.io/embed/rl9ykvlvvp], so the test can finish(it is failing because of the test condition.)

I think using a saga's test library to test your code might be better than using this particular strategy from the doc.

**Comment by mean2me** [comment]
Thanks a lot @zhaoyingdu !
Actually I was missing that part. I'm gonna update my test code and share the working example for other people.
