### ISSUE TITLE
TypeScript error when using predicate as the first argument of takeEvery effect

### ISSUE THREAD

**Issue by vasilii-kovalev** [redux-saga/redux-saga#1871]
I have such code in my app (Create React App with TypeScript):
```typescript
export default function* rootSaga() {
  yield all([
    handleAPIRequestSaga, // common saga for the whole app.
  ]);
}
```
```typescript
interface HandleAPIRequest {
  prefix: string;
  status: string;
  request: () => Promise<any>;
}

const handleAPIRequestSaga = takeEvery(
  ({ status, request }: HandleAPIRequest) => (
    // requestStatuses.start is 'START'
    isEqual(status, requestStatuses.start) && request
  ),
  handleAPIRequest,
);
```
And TypeScript says the following:
![image](https://user-images.githubusercontent.com/10310491/59563724-6fd74480-9046-11e9-8e6c-29a93963a9d3.png)

Is it correct behavior or not? If it is correct, what approaches to solve the error there are?

`redux-saga`: 1.0.3
`typescript`: 3.5.2

Thanks in advance.

**Comment by osoftware** [comment]
Same issue for ```take```.

**Comment by Andarist** [comment]
`HandleAPIRequest` doesnt seem to be assignable to action type (it doesnt have type property), this makes TS to try next overload on which it fails again (as its not channel either) and it only reports error on last overload even though all of them have failed.

**Comment by vasilii-kovalev** [comment]
@Andarist, in this case `type` is not necessary at all to make a decision whether `handleAPIRequest` should handle the action or not. Are there any approaches and/or solutions for cases like this?
For now I refused TypeScript to keep moving on, but if there will be any solutions I'd like to return to strict typing.

Here you can find a project with the described architecture:
https://codesandbox.io/s/react-with-redux-saga-07wlh

One more thing: when I download the project, install the dependencies and try to run the app, `tsconfig.json` file is created automatically, and after that I can see the error. I added the file to CodeSandbox manually, so you can see the error too. Without it Codesandbox doesn't show any errors related to TypeScript.

**Comment by Andarist** [comment]
Hm, I'm not sure why this doesn't work. I believe you have to add `type` property to your type (you might just do `extends Action`), but even with that this doesn't want to be matched. Any property added to Action type (when extending) make it fail. Maybe @aikoven could help with investigating this.

**Comment by aikoven** [comment]
I think @Andarist is right, the `HandleAPIRequest` type should be assignable to `Action` so that TypeScript could infer which one of `takeEvery` signatures it needs to use.

**Comment by marcandrews** [comment]
I have been struggling with this myself. My actions `extend Redux.Action`.

If I comment out the [channel-related `takeLatest` definition overloads](https://github.com/redux-saga/redux-saga/blob/master/packages/core/effects.d.ts#L199-L204), I think I get the real error: 
```
Argument of type '(action: ActionWithPayload<actionTypes, { provider: PROVIDERS; }> | ActionWithPayload<actionTypes, { provider: PROVIDERS; }> | ActionWithPayloadAndMeta<actionTypes, { passport: PassportType; }, { provider: PROVIDERS; }>) => boolean' is not assignable to parameter of type 'ActionPattern<Action<any>>'.
  Type '(action: ActionWithPayload<actionTypes, { provider: PROVIDERS; }> | ActionWithPayload<actionTypes, { provider: PROVIDERS; }> | ActionWithPayloadAndMeta<actionTypes, { passport: PassportType; }, { provider: PROVIDERS; }>) => boolean' is not assignable to type 'Predicate<Action<any>>'.
    Types of parameters 'action' and 'arg' are incompatible.
      Type 'Action<any>' is not assignable to type 'ActionWithPayload<actionTypes, { provider: PROVIDERS; }> | ActionWithPayload<actionTypes, { provider: PROVIDERS; }> | ActionWithPayloadAndMeta<actionTypes, { passport: PassportType; }, { provider: PROVIDERS; }>'.
        Type 'Action<any>' is missing the following properties from type 'ActionWithPayloadAndMeta<actionTypes, { passport: PassportType; }, { provider: PROVIDERS; }>': payload, meta ts(2345)
```

Please see this [CodeSandbox](https://codesandbox.io/s/dry-lake-wh5jq) that reproduces the error.

Any help will be greatly appreciated.

**Comment by marcandrews** [comment]
Actually, I may have a fix. See #1895.

**Comment by aikoven** [comment]
I don't think that the fix is correct. `take` expects `Predicate<Action>` for a reason — it should accept *any* action, i.e. any object with `type` field.

To fix your case, you have several options:

You could cast `action` to `ActionWithPayload`, like this:
```ts
(action as ActionWithPayload<...>).payload.passport.provider === provider
```

Otherwise, you could replace `type` comparison 
```ts
action.type === actionTypes.PASSPORT_REQUEST_SUCCESSFUL
```
with some function that returns a [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) that tells TypeScript that `action` is `ActionWithPayload<...>`. This approach is used in [aikoven/typescript-fsa](https://github.com/aikoven/typescript-fsa).

Another option is to augment `redux-saga` types to consider your actions:
```ts
declare module 'redux-saga/effects' {
  export function take(pattern: Pattern<actions>): TakeEffect
}
```

**Comment by marcandrews** [comment]
There is no need to use casts or type guards when you can use [discriminated unions](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions) to infer the type of `action` automatically.

In my honest opinion, the approach to typing a Redux system has been well-established and you create a union of all actions. In your you reducer, you can use this union to ensure the state of the application given all the possible actions.

As soon as you code `action.type === actionTypes.PASSPORT_REQUEST_SUCCESSFUL` or `switch (action.type) { case actionTypes.PASSPORT_REQUEST_SUCCESSFUL: ...`, TypeScript can infer the type of the `PASSPORT_REQUEST_SUCCESSFUL` action.

If you look at this [unit test](https://github.com/redux-saga/redux-saga/blob/v1.0.5/packages/core/__tests__/typescript/effects.ts#L46), you will see that this type guard does not work as TypeScript does not know that `.customField` is a property of `action`

<img width="1005" alt="Screen Shot 2019-08-10 at 8 21 32 AM" src="https://user-images.githubusercontent.com/3518829/62821777-2be55500-bb48-11e9-8283-b85670456105.png">

If you look at the [`ActionSubPattern` union](https://github.com/redux-saga/redux-saga/blob/v1.0.5/packages/types/index.d.ts#L26-L30) that take uses, `Guard extends Action`, so it should be `Predicate<Guard>`, similar to the other types in this union.

If it is `Predicate<Action>`, `Predicate<T> = (arg: T) => boolean` becomes `Predicate<Action> = (arg: Action) => boolean`, and because `Action` only has a `type` property, it forces you to cast or guard the type of `action` in the predicate.

With `Predicate<Guard>`, `Guard` becomes your actions union and now TypeScript can use discriminated unions to infer the type of action in the predicate, no casts or guards required.

I will update #1895 and utilize an actions union in the unit to exemplify.

**Comment by aikoven** [comment]
I agree that using discriminating unions is a valid and reasonable style for Redux. 

But the proposed change does not seem correct to me. The meaning of the type parameter of `ActionSubPattern` is the type of all actions matched by the pattern. `Predicate<Guard>` is not a predicate that acts on actions from `Guard`; it is a predicate that acts on any action, but returns `true` only for actions from `Guard`.

So by default patterns and predicates in particular act on the whole space of actions which is defined by `Action` type. What you need to do is to narrow down that space to a particular union of actions.

`take` and friends don't know whether you're using discriminated unions, and even if they did, you would have to somehow get `redux-saga` typings to know your particular union type. This can be achieved by augmentation or introducing another type parameter for `take` etc. Maybe there's a more elegant way.

**Comment by vasilii-kovalev** [comment]
It seems, there were no discussions about the topic for a long time, and I don't use `redux-saga` anymore, so I closed this issue.
Feel free to reopen it if necessary.
