### ISSUE TITLE
watcher run without dispatch.

### ISSUE THREAD

**Issue by VuongVu** [redux-saga/redux-saga#1898]
Hi, i have a problem with redux-saga using in my NextJS project.
I declared 2 watcher and wrap it with rootSaga. I just dispatch action for load watcher 1 but watcher 2 always call.

This is my gist to review the bug: https://gist.github.com/VuongVu/4e9d7e2fe9751b5b04783324aa84ead0.
Plz review it and give me a solution for it. thanks so much

**Comment by lindboe** [comment]
It's a little hard to be sure what's going on because your patterns for the `take` calls, `loadCoursePreview` and `loadLessonPreview`, aren't defined in the gist. But I think I can understand enough to be helpful.

In your `mapDispatchToProps` function, you call `loadCoursePreview` as a function. Based on this, I'm going to assume `loadLessonPreview` is also a function. Most likely an action creator.

When `take` is given a function as its `pattern`, there will be a successful match if that function returns a truthy value with the action as an input (https://redux-saga.js.org/docs/api/#takepattern). Since action creators _usually_ just return an object, you're always getting a truthy result.

I think what you want instead is to provide the action `type` to `take` as a string, rather than the functions that create the actions. E.g., `take('load_course_preview')`. I suppose if you have an action creator here, you could create the action and get the type field: `take(loadCoursePreview().type))`

Did I understand correctly?

**Comment by VuongVu** [comment]
yes, thank you very much for solving the problem 👍
