### ISSUE TITLE
lodash/fp/allPass result not working as pattern

### ISSUE THREAD

**Issue by krutoo** [redux-saga/redux-saga#1950]
Hi. This example show that allPass result function not called by redux-saga (i just dispatch action from component but first `takeEvery` not working, only second):

```javascript
import { call, takeEvery } from "redux-saga/effects";
import allPass from "lodash/fp/allPass";
import propEq from "lodash/fp/propEq";

export function* testAllPass() {
  yield call(alert, "test action handled! by allPass pattern");
}

export function* testFunction() {
  yield call(alert, "test action handled! by function");
}

export default function* rootSaga() {
  // it is not working
  yield takeEvery(
    allPass([
      // for calling test
      action => {
        alert("Its called");
        return true;
      },
      propEq("type", "TEST"),
      propEq("foo", "bar")
    ]),
    testAllPass
  );

  // it is working
  yield takeEvery(
    action => action.type === "TEST" && action.foo === "bar",
    testFunction
  );
}
```

Please help me resolve a problem. Thanks.

**Comment by Andarist** [comment]
Please prepare a runnable repro case (might be on codesandbox)

**Comment by krutoo** [comment]
> Please prepare a runnable repro case (might be on codesandbox)

Here:
https://codesandbox.io/s/redux-saga-example-i9gb5?fontsize=14

**Comment by Andarist** [comment]
Those lodash wrappers (like allPass) are created with internally with `baseRest`:
https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L3928
which in turn uses `setToString`:
https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L4016-L4023

We detect own `toString` methods and try to call them if they are present and compare `action.type` against returned value. Why? Because there are bunch of redux-related librararies with action creators factories which creates action creators with toString returning `action.type` to avoid some boilerplate, that way you can do things like:
```
const reducer = createReducer({
  [actionCreator.addTodo]: (state, addTodoAction) => return state
})
```

I have no idea why lodash is trying to set toString on returned methods, it doesn't seem to give much and can only IMHO trip people up. Maybe it's worth reporting this to them as from what I see they are refactoring the codebase right now, presumably getting ready to release v5 (this is just my guess) - so maybe you could raise that issue there (not this specific one, as they probably dont care about redux-saga, but rather the fact that they override toString and would be good to know why).

**Comment by krutoo** [comment]
Creator of Lodash replied: https://github.com/lodash/lodash/issues/4512#issuecomment-542902869

Now I do not know what to do) I just can't use two good libraries along with convenience...
