### ISSUE TITLE
Should I handle UI logic inside saga?

### ISSUE THREAD

**Issue by dangdien-tiki** [redux-saga/redux-saga#1970]
Hi, I have some UI helpers from [antd](https://ant.design/) to push notification by just call `notification()` or to open a error modal by `modal.error()`.

Now for instance, I have a fetch action, I want to push a notification if the fetch succeeded, and open a error modal if the fetch failed. I cound just do it like this:

```js
import { notifcation, modal } from 'antd'

//...

const { response, error } = yield call(fetchSomething)

if (response) {
  notification('fetch succeeded!')
} else {
  modal.error('something wrong')
}
```

this is ok but I'm thinking about at some point in the future, I will need to change the UI library, or moving to react-native for instance, so I'd have to refactor if I'm mixing the UI logic with application logic (saga) like the above example. The main point is **I want to separate saga from UI logic**.

I wonder if there is a best practice about handling UI logic with redux-saga. The ideal solution would be saga taking care of app state only, so I can later reuse that whole saga for different UI components set.

**Comment by ilias-t** [comment]
>The ideal solution would be saga taking care of app state only, so I can later reuse that whole saga for different UI components set.

Yeah, that sounds like the solution right there. If the goal is to have redux saga be agnostic of whatever the UI, which is a sensible goal then just have redux saga dispatch actions that update the state and have the UI subscribe to that state for what to do. 

In the case of showing a notification, you could dispatch and action that updates the state of the notification store to something along the lines of `activeNotification` being set to `{ type: Notification.SUCCESS, message: 'whatever' }` and then once that state is consumed by the UI, the message is shown and thereafter cleared from the redux state.

Modals are likely pretty similar, where a saga just updates the state to whichever modal, in any, should be displayed.

**Comment by hilkeheremans** [comment]
As @ilias-t mentions, ideally, you would take care of app state only with redux-saga. However, sometimes you need to be more pragmatic and allow some coupling here and there between what happens in your UI and redux-saga, especially when, as in this case, it involves imperative code you need to call somewhere.

For such cases you can consider still using redux-saga to trigger things like modals, but partially decoupling it from your real business logic by adding a simple abstraction layer and moving the saga code that is tightly coupled to your UI to a different location.

**In this particular case**, you could for example abstract away the notification and error cases by, instead of directly calling the UI code here, putting two actions (ie a FETCH_SUCCESS and FETCH_FAILURE action), and have a different saga domain (ie a UI domain) listen to those actions, and act appropriately by calling `notification` or `modal.error` there.. While one domain (the UI domain) will still be tightly coupled to your specific UI library, the rest of your code will remain decoupled and should be reusable.

The reason why I generally prefer this approach is that it beats putting this stuff in state, then creating some react component that reacts to a state _change_, causing it to call some notification.show. I try to avoid patterns where you artificially set a piece of state in order to trigger prop switches in a component, which then from that component trigger imperative code (arguably though, in this age of `useEffect` that view is easier to contest :-)).

**Comment by dangdien-tiki** [comment]
@hilkeheremans yes, what you said is exactly what I'm doing right now. Abstracting UI logic seems to be the best choice for this case. So later if I move to another UI library, all I need to do is updating the UI "domain" without touching my pure-app-logic saga.

One more tricky part is for other side effects like accessing local storage, or even calling `window.open` to open another tab are also need to be abstracted. The logic saga then do nothing but takes an action and dispatching other actions.

**Comment by neurosnap** [comment]
Based on my years of experience using redux-saga, I would recommend not dealing with UI logic inside of sagas.  It makes the separation between UI and business logic mixed and leads to all sorts of issues downstream.  Happy to continue chatting about this inside a new GH discussion if you are interested.  Thanks!
