### ISSUE TITLE
@redux-saga/simple-saga-monitor changes global scope (on import

### ISSUE THREAD

**Issue by ashirley** [redux-saga/redux-saga#1978]
# Steps to reproduce

#### Description of the bug/issue
Global scope is modified (`$$LogSagas` is added) and console.log is called.

#### Steps to reproduce the bug/issue
import (but don't use) sagaMonitor as follows:
`import sagaMonitor from '@redux-saga/simple-saga-monitor';`

# Possible Solution

Would it be reasonable to do this only when the root saga is run instead?

**Comment by Andarist** [comment]
Could you give more details on why this is a problem for you? I would like to understand the concrete use case to establish what's the best way to fix this.

Keep also in mind that this package is meant more as an example of how one can implement a saga monitor rather than a tool that is supposed to be used directly at scale.
