### ISSUE TITLE
Cancellation is broken for sequenced sagas

### ISSUE THREAD

**Issue by jonrimmer** [redux-saga/redux-saga#1986]
### Steps to reproduce

```js
function* subSaga() {
  try {
    yield put(SHOW_SPINNER);
    yield call(longRunningTask);
  }
  finally {
    yield put(HIDE_SPINNER);
  }
}

function* saga() {
  yield* subSaga();
  console.log('Should never be executed during cancellation.');
}
```

#### Description of the bug/issue

If a sequenced saga uses try/finally, the parent saga continues to run even after it has been cancelled.

If `saga()` is cancelled while `subSaga()` is running, it should never reach the `console.log()` statement, but it does.

#### Example

https://codesandbox.io/s/redux-saga-issue-template-nr9to

Click on the "increment after 5s" button. The increment saga will be started than automatically cancelled after 1s.

### Actual results

The following is logged:

```
subSaga cancelled 
(saga) I should never be executed during cancellation. 
saga cancelled 
```

### The Expected results

```
subSaga cancelled 
saga cancelled 
```

### Environment information

 - redux-saga v1.1.3

**Comment by shinima** [comment]
Actually this is the expected behavior.  Let me try my best to explain it for you...  😅

Cancellation is implemented based on task model. When you call `yield cancel(someTask)`, redux-saga will trigger the cancellation of `someTask` and all of its children. 

When you call `yield call(...)` or `yield subSaga()` or `yield fork(...)`, redux-saga will create a child task and attach it to the parent task; However when you call `yield *subSaga()`, sequence (or generator delegation) is handled by JavaScript engine itself, redux-saga has no chance to create a child Task object.

In your example, cancellation to `saga` is delegated to `subSaga`, and `subSaga` will be cancelled and then it is returned. In `saga`'s view, `yield* subSaga()` is returned normally (with a strange return value), and `console.log('Should never be executed during cancellation.')` is executed then.

**Comment by jonrimmer** [comment]
Thanks for the explanation. Still not sure I fully understand, but I'll take your word for it this is intended! ;-)
