### ISSUE TITLE
On Reload persist the store data

### ISSUE THREAD

**Issue by jigardarji318** [redux-saga/redux-saga#2006]
Hi Team,

Can you please tell me how to persist store data when refreshing the URL?

### Description
Please provide some context about the problem and some code examples if relevant.
The best way to provide an example is repository or use [Code Sandbox](https://codesandbox.io/)(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

**Comment by Andarist** [comment]
This is a question, so it really would be best suited for StackOverflow rather than issues on GitHub. It's too hard to give you an answer without knowing more details about your problem, you have to figure out what strategy would work for you and implement it, most likely, in a custom manner (designed to handle your use case).
