### ISSUE TITLE
select returns unknown type with typescript 3.6.5

### ISSUE THREAD

**Issue by tommybernaciak** [redux-saga/redux-saga#2015]
### Steps to reproduce
```
export const getUserInterface = (state: IStore): IUserInterface => {
	return { drawerWidth: state.ui.drawerWidth };
};
const ui: IUserInterface = yield select(getUserInterface);
```

#### Description of the bug/issue
This used to work well with Typescript 3.4.5, but I updated to 3.6.5. Now I see an error `Type 'unknown' is not assignable to type 'IUserInterface'.` I have it all over my application and it seems that `yield select()` always returns `unknown` type. I didnt find any workaround.

### Environment information
- redux-saga 1.1.3
- typescript 3.6.5

**Comment by Andarist** [comment]
@gilbsgilbs would you be able to assist with this issue?

**Comment by gilbsgilbs** [comment]
Hi!

Your repro lacks some information because you're using `yield` outside of a generator function. To give you a precise answer, I think we need the actual prototype you use to declare your sagas.

Anyways, although I have not encountered this specific issue myself when updating TS, the error is just stating about [the way `unknown` type works](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type). I can glimpse at least 3 solutions to your issue:

```typescript
// 0: Use Generator type and manually set TNext to any
function* mySaga(): Generator<StrictEffect, void, any> {
  const ui: IUserInterface = yield select(getUserInterface);
}

// 1: Use SagaIterator type (which already has TNext set to any)
function* mySaga(): SagaIterator<void> {
  const ui: IUserInterface = yield select(getUserInterface);
}

// 2: Deal with the unknowns the way TS intends you to do
function* mySaga(): Generator<StrictEffect> {
  // This is how you assign `unknwon` in TS: you just cast it *before* assigning.
  // Type inference does the rest.
  const ui = (yield select(getUserInterface)) as IUserInterface;
}
```

The latter solution definitely has my vote here because it is the intention behind the `unknown` type. It forces you to specify the type of the object explicitly, as soon as you receive it, even before you assign it. This is an improvement regarding type safety.

BTW, you might want to look at #2008. It would allow type inference to work and remove the need for explicit casting.

**Comment by tommybernaciak** [comment]
Ok, thanks, I will use it as a workaround. But for me personally, this should be fixed somehow. If I defined a selector function with return type  I expect this type will be returned after yield.

**Comment by Onatolich** [comment]
Hi! Is there any updates on this topic?

**Comment by Cubelaster** [comment]
I have the exact issue. 
After npm update, solution breaks because of this.
Would also expect the return type from selector function to work.

**Comment by ahmad2smile** [comment]
would be great if we didn't have to cast it

**Comment by Artyom-Ganev** [comment]
Still actual

**Comment by neurosnap** [comment]
Better typing in redux-saga is a limitation with typescript, please see https://github.com/microsoft/TypeScript/issues/43632

Closing this issue for now.  Thanks!
