### ISSUE TITLE
What is a proper way to close an eventChannel

### ISSUE THREAD

**Issue by meteorra** [redux-saga/redux-saga#2022]
Hi, are there any approaches how to destroy eventChannel, that should exist all the time that application is live & there's no particular event to fire close() method on a channel. Is it ok just to provide an unsubscribe function as a return value? Will this function be ever fired then on any internal event like destroying parent saga or something else? I don't see that this function is ever called rather than when I manually call purchaseChannel.close(). My concern is that each time parent saga is run, it could potentially add new event listener without removing previous ones.
```javascript
const purchaseChannel = eventChannel(emit => {
  const listener = (purchase: Purchase) => {
    emit(purchase)
  }
  const purchaseListener = eventEmitterInstance(listener) // event emitter with a subscribed listener
  return (): void => {
    purchaseListener.remove()
  }
})
```

**Comment by Andarist** [comment]
You need to manually close it because `eventChannel` is not yielded to the saga runtime, so it has no means to close it automatically as it's not even aware of its existence. 

```js
function *saga(){
  const chan = eventChannel(() => {/* */})
  try {
    while (true) {
      const ev = yield take(chan)
      /* do smth with ev */
    }
  } finally {
    chan.close()
  }
}
```

**Comment by meteorra** [comment]
I assume that it'll be the same thing:
```
function *saga(){
  const chan = eventChannel(() => {/* */})
  try {
    yield takeEvery(chan, chanListener)
  } finally {
    chan.close()
  }
}
```
Is my understanding correct?

**Comment by Andarist** [comment]
Not quite, but in general - yes you can extract your handler and use takeEvery with it.

The difference is that `takeEvery` creates a task descriptor and returns it synchronously to the caller, so your saga will continue its execution and will jump to this finally block immediately.

You need to "block" the saga, so the finally block can only be executed when saga runtime decides to cancel this whole subtree of sagas or an uncaught error gets thrown. You can, for example, abuse `join` effect to do this, because `takeEvery`'s internal saga never returns:

 ```js
function *saga(){
  const chan = eventChannel(() => {/* */})
  try {
    const task = yield takeEvery(chan, chanListener)
    yield join(task)
  } finally {
    chan.close()
  }
}
```

Algternatively you can create a more explicit helper for this:
```js
const blocker = () => new Promise(() => {})
const block = () => call(blocker)
```
which you could use like this:
```js
yield block()
```

**Comment by meteorra** [comment]
Got it, thank you!
