### ISSUE TITLE
How can I cancel all flushed tasks in a channel OR restart a channel after cancelling it?

### ISSUE THREAD

**Issue by jjoselv** [redux-saga/redux-saga#2037]
### Description

I have an **action that is triggered every X seconds (polling)**, and the saga that handles this action contains several `call`s and `put`s, so **it may take some time to complete**. The thing is that at the start of the saga I do a `call`, and the path that is followed inside the saga depends on the JSON response of this first `call`. Also **at the end**, when detecting an end condition in this JSON, **I launch a `put` to stop this polling**.

I wanted to make sure that every action is handled so I don't run into race conditions, so I though I may use a channel for this.

The main issue I have is that I cannot find a way to flush and then cancel remaining buffered tasks (to prevent unwanted saga runs when I stop the polling function), neither to restart the created channel, to effectively discard the queued tasks and thus keep the channel listening.

**Comment by Andarist** [comment]
Could you paste in pseudocode of what you are doing right now? Would be better if I could branch of it with a suggestion than writing the whole thing on my own.

**Comment by jjoselv** [comment]
```javascript

const loadApplicationDataSaga = function* (action, channel) {
    //make api call
    const {data} = yield call(() => api.resources.applicationPolling.get());
    if (data.doing) {
       const {data} = yield call(() => api.resources.application123.post());
       yield put({
            type   : actions.UPDATE_STATE,
            payload: {
              foo: "bar"
            }
       });
    }
    if (data.done) {
      yield put({
            type   : actions.STOP_POLLING,
      });
      // maybe flush channel? close channel? restart channel? 
    }
}

const watchLoadApplicationData = function* () {
    const channel = yield actionChannel(actions.LOAD_APPLICATION_DATA)
    while (true) {
        const action = yield take(channel)
        yield loadApplicationDataSaga(action, channel);
    }
}

const etherProjectCreationWizardSagas = [
    takeLatest(actions.LOAD_PROJECTS, method1),
    watchLoadApplicationData(),
    takeLatest(actions.LOAD_USERS, method12),
];

export default sagas;
```

**Comment by Andarist** [comment]
I'm not entirely sure if I understand your requirements correctly. What I have understood is that:
- you dont want to execute `loadApplicationDataSaga` multiple times in parallel
- each `LOAD_APPLICATION_DATA` should result in `loadApplicationDataSaga` being called, but it's not a problem to queue a task if there is `loadApplicationDataSaga` already executing at the time 
- there is a requirement for canceling those queued tasks when you meet a condition inside `loadApplicationDataSaga`

If that's all then you could just flush that channel inside - that would empty it (and thus all "queued" tasks). You would still wait for new `LOAD_APPLICATION_DATA` to happen from that moment, I assume that it's what you want.

While this would work and it seems like a simple solution for the problem it introduces a particular imperative coupling between the parent (`watchLoadApplicationData`) and the child (`loadApplicationDataSaga`) because you allow the child to manipulate parent's state directly - without the parent knowing about it. You could try to eliminate it by introducing a little bit more generic and flexible approach. Keep in mind that this might not be worth it - depending on your needs and taste. I mostly want to showcase this for educational purposes, so don't take it for a definitive answer. The answer is always "it depends" 😉 

A way to do introduce a nice parent-child communication:
```js
const createActorChannel = handler =>
  call(function*() {
    const chan = channel(buffers.none());
    yield spawn(function*() {
      while (true) {
        // handler is on purpose a synchronous function
        handler(yield take(chan));
      }
    });
    return chan;
  });

const loadApplicationDataSaga = function*(action, parentChannel) {
  //make api call
  const { data } = yield call(() => api.resources.applicationPolling.get());
  if (data.doing) {
    const { data } = yield call(() => api.resources.application123.post());
    yield put({
      type: actions.UPDATE_STATE,
      payload: {
        foo: "bar"
      }
    });
  }
  if (data.done) {
    yield put({
      type: actions.STOP_POLLING
    });

    yield put(parentChannel, { type: "FLUSH" });
  }
};

const watchLoadApplicationData = function*() {
  const channel = yield actionChannel(actions.LOAD_APPLICATION_DATA);

  const actorChannel = yield createActorChannel(action => {
    switch (action.type) {
      case "FLUSH":
        channel.flush();
        return
    }
  });

  while (true) {
    const action = yield take(channel);
    yield loadApplicationDataSaga(action, actorChannel);
  }
};
```

A pattern like this is more robust and allows you to create a "supervisor" for many workers with multiple action types, but more importantly - it allows you to keep the parent's state isolated.

**Comment by jjoselv** [comment]
Thanks for your answer!
I was wondering, if flushing the channel (buffer) would immediately start all the sagas that were buffered, or on the contrary it would "discard" them.

**Comment by Andarist** [comment]
Channels on some level are just fancy arrays (FIFO queues) and flushing is literally `arr.length = 0` to them 😅 You also don't (usually) store sagas in them but rather simple objects - such as actions.

**Comment by jjoselv** [comment]
I see! :)
Also, why `buffers.none()`? I want to have a buffer so that I can queue them, only when I want to finish the process I'll call `flush`

**Comment by jjoselv** [comment]
I see what you did, buffer for the actionChannelCreator, not the other one.
Thanks A LOT!!!! Let me try to understand the actionChannelCreator code :) (too complex for me hehe)

**Comment by jjoselv** [comment]
Hi again, it seems that the `yield put(parentChannel, { type: "FLUSH" });` never launches the saga. I put a log there and, it doesn't reach that line.

**Comment by Andarist** [comment]
Could you prepare a runnable repro case on CodeSandbox?

**Comment by jjoselv** [comment]
Nevermind, It worked perfectly! Thanks!
