### ISSUE TITLE
How to define compensation in redux-saga?

### ISSUE THREAD

**Issue by Airwavess** [redux-saga/redux-saga#2057]
Saga pattern defines that each transaction has a corresponding compensation. However, I cannot find any information about compensation in the official documents.

So, how to define compensation in redux-saga?

Does Compensation means that redux-saga can use try-catch to compensate an action or use cancellation to compensate an action ?

**Comment by pohsiu** [comment]
Same question

**Comment by Andarist** [comment]
Redux-saga is loosely based on the Saga pattern. In most frontend applications we don't deal as much with transactions as on the backend that's why there is no focus on this in the docs. 

I believe that this should be implemented using event-based techniques and you should inform the previous step in the saga with a rejection event which it should handle according to its rules (compensate over a rejected part of a transaction that it is responsible for).

**Comment by zdzarsky** [comment]
Personally I'd vote such a feature. 
I've found the workaround. According to the fact that compensation is also a "saga" that ensures semantic correctness, you might throw from main saga and compensate it in a following way:
```
type SagaWithCompensation = (
  handler: any,
  saga: any,
  ...args: any
) => (action: any) => Generator<CallEffect<unknown>, void>


export const withCompensation: SagaWithCompensation = (saga, compensationSaga, ...args: any) =>
  function* compensationGenerator(action: any) {
    try {
      yield call(saga, ...args, action)
    } catch (err) {
      yield call(compensationSaga, ...args, action, err)
    }
  }
  ```

**Comment by neurosnap** [comment]
Closing as it looks like there was a resolution.  Thanks!
