### ISSUE TITLE
Assigning the result to variable when yield another generator function

### ISSUE THREAD

**Issue by zanfirandra** [redux-saga/redux-saga#2123]
### Description
Hello,

I'm trying to understand how plain generator functions works and also in `redux-saga` context. So I'm having this situation described here in [codesanbox ](https://codesandbox.io/s/yield-function-3r54o)

These are the following generator functions
```javascript
function* userInfo() {
  return "John";
}

export function* helloSaga() {
  console.log("get data");
  const name = yield userInfo();
  console.log("name: ", name);
}

```
which are used in `store/sagas.js` and also in `index.js` as plain generator functions on which I call `next()` method on.

When used in `index.js` I'm expecting that `name` it should be `undefined` because I'm not passing any argument to `next` function.
> If an optional value is passed to the generator's next() method, that value becomes the value returned by the generator's current yield operation. - MDN

But used in redux-saga context, it actually assigning the result of the yield  to `name` variable. So my question here is how does this work?  I'm just curious about the mechanism behind this. Also is this a right way of doing this? Or should I always use effect creators like `fork` even if it works without?

**Comment by Andarist** [comment]
It works in the context of saga because iterators are recognized as valid yielded values that are being interpreted by our runtime. So just how we interpret yielded fork/call/whatever effects we are capable of interpreting iterators - which you have yielded to use here `yield userInfo()`. And as we handle this on our own - we can do whatever we want 😉 `yield userInfo()` is basically interpreted in the very same way as `yield call(userInfo)`.

**Comment by zanfirandra** [comment]
Nice :fire: I understand now, thank you!
