### ISSUE TITLE
actionChannel has a wrong typescript return type

### ISSUE THREAD

**Issue by MaxShymko** [redux-saga/redux-saga#2197]
#### Description of the bug/issue
actionChannel returns `ActionChannelEffect` type:
```js
type ActionChannelEffect = SimpleEffect<'ACTION_CHANNEL', ActionChannelEffectDescriptor>
```

But `take` effect accepts only `TakeableChannel` type:
```js
interface TakeableChannel<T> {
  take(cb: (message: T | END) => void): void
}
```

#### Example
[see codesandbox](https://codesandbox.io/s/compassionate-cloud-e8m1p?file=/src/index.tsx:592-596)
```js
const chan = (yield actionChannel('TYPE')) as ReturnType<typeof actionChannel>;
yield take(chan); // Typescript error here
```

### Actual results
Typescript error:
Argument of type 'ActionChannelEffect' is not assignable to parameter of type 'TakeableChannel<unknown>'.
Property 'take' is missing in type 'SimpleEffect<"ACTION_CHANNEL", ActionChannelEffectDescriptor>' but required in type 'TakeableChannel<unknown>'.

### The Expected results
In runtime `chan` contains the following methods:
close: ƒ ()
flush: ƒ flush(cb)
put: ƒ put(input)
take: ƒ take(cb)

I expect that `actionChannel` should have a return type that covers all the above methods.

### Environment information
redux-saga: 1.1.3
typescript: 4.3.2

**Comment by Andarist** [comment]
The type is correct - `actionalChannel` is an effect and it does not return a channel directly. It return an effect instructing Redux-Saga runtime to create such channel:
https://github.com/redux-saga/redux-saga/blob/9e7b2973283142eaded86da9686896dbf8522a64/packages/core/src/internal/io.js#L240-L251

It's like you would like to treat `call` effects as their results. This won't work:
https://codesandbox.io/s/exciting-wildflower-68mbm?file=/src/index.tsx

**Comment by MaxShymko** [comment]
Thank you for the answer. You are definitely right, I caught the difference.

Could you provide an example of how I should rewrite the code?

Do I have to use the `Channel` type for this channel?
```js
const chan = (yield actionChannel('TYPE')) as Channel<unknown>; // what should be used instead of unknown?
```

**Comment by ikusteu** [comment]
@MaxShymko , thank you for bringing this up, I've had the same problem and this helped me find a solution. From what I see in the `Channel<T>` interface declaration, it includes some methods such as `put(message: T | END): void`. Therefore, considering the way data is passed to `put` helper, It makse sense to me to use your redux action interface i.e. 

```typescript
interrface ActionInterface {
  type: "TYPE"
  payload: ActionPayload // whichever
}

const chan = (yield actionChannel('TYPE')) as Channel<ActionInterface>;
```

However, this doesn't solve much, as I still have to cast types to the `take` helper listening to this channel i.e.

```typescript
while (true) {
  const { payload }: { payload: ActionPayload } = yield take(chan) // the payload type here wouldn't be infered
  yield call(handlePayload, payload)
}
```

I think this is because `put`, `call`, `take`, `actionChannel` etc. return effects (instructions to the middlewate rather then async actions) and the type is lost (cast to any) at yield. 

I don't know if this is a typing inconsistency with saga helpers/effects in general or if there's a better way.

**Comment by neurosnap** [comment]
I’m going to close this issue for now as it looks like there was a resolution.  Please feel free to open ask any questions here and I’d be more than happy help.
