### ISSUE TITLE
How is Redux Saga actually related to the Saga pattern?

### ISSUE THREAD

**Issue by andremarcondesteixeira** [redux-saga/redux-saga#2304]
### Description
The documentation mentions the saga pattern. It gives us some resources and even a link to the original paper. I did read the paper. and then I got confused. What does redux saga have to do with the saga pattern and LLT's? In javascript we don't need to block stuff, so I really don't get how the saga pattern is implemented in redux saga and the documentation does not provide any explanation on HOW this pattern is implemented. Where are the cancellations? the backward recovery process? the forward recovery process? What is being broken into multiple transactions? I don't get it and the docs don't bother to explain.

**Comment by andremarcondesteixeira** [comment]
P.S: I never used Redux-Thunk, so comparing redux saga to it is not helpful

**Comment by neurosnap** [comment]
The `saga` term has been stretched slightly in the context of this library.  Here's a very old gh issue discussing the usage of saga:  https://github.com/redux-saga/redux-saga/issues/70#issuecomment-181397054

Let me take a stab at answering your questions.

>  What does redux saga have to do with the saga pattern and LLT's?

When you setup redux-saga in your FE codebase, you register a single saga.  That saga will contain within it, an infinite loop.  That saga will never shut down until the user closes the app (or there's a failure and it doesn't recover).  Most of the time, that single saga will call other sagas.  They will also contain infinite loops within them.  Most of the time, these sagas will wait and listen for events (actions being dispatched) and then perform long-running tasks.

> In javascript we don't need to block stuff

Hmm, I'm not entirely sure what you mean here, but I'll take a stab.  In the browser, the javascript operates on a single thread.  Blocking that thread is highly discouraged because then the user cannot interact with the page at all.  So in that sense, we don't want to block stuff.  

However, when it comes to async flow control, we do want to wait for certain operations (or transactions) to complete before proceeding to the next step.  For example, we want to wait to fetch an API endpoint before trying to process its results.

> [...] the documentation does not provide any explanation on HOW this pattern is implemented

Agreed. We have it on our roadmap to work on cleaning up the documentation, including answering questions like the ones you posed.  Thank you for your feedback!

> Where are the cancellations?

https://redux-saga.js.org/docs/advanced/TaskCancellation

> the backward recovery process?

Undoing transactions is something the end-developer needs to implement.  We provide the tooling to support saga failure.  Backward recovery could be as simple as a try/catch inside a saga:

```js
function* saga() {
  try {
    yield put(addUser(...));
    yield call(doSomethingThatFails);
  } catch (err) {
    yield put(removeUser(...));
  }
}
```

> the forward recovery process?

Similarly to backward recovery, forward recovery would have to be implemented by the end-developer.

> What is being broken into multiple transactions?

With redux-saga, you only register a single, root saga.  This is similar to a root reducer.  That saga spawns many other long-lived sagas, all doing their own thing.  This creates a tree data structure of long running tasks that all perform their own series of "transactions" or side-effects.  Sagas will interact with APIs, websockets, and redux store (the FE in-memory DB).
