### ISSUE TITLE
Recent improvements not published

### ISSUE THREAD

**Issue by lourd** [redux-saga/redux-saga#2319]
Hey @Andarist & @neurosnap,

Please publish a new version of the packages. It's been 6-24 weeks since each of these PRs were merged:

#2270
#2293 
#2295
#2296 
#2297 

Is there anything blocking new versions from being published?

**Comment by Andarist** [comment]
I just want to land this before the release: https://github.com/redux-saga/redux-saga/pull/2308

**Comment by lourd** [comment]
Gotcha. I understand the motivation to wait on it and publish them all together in one release, but do you think you could do a small one without it?

Specifically, it would be really helpful if we could publish the update to `testing-utils`. I've been making do with a patched package, but I need one of the other changes we made to `createMockTask`, and trying to update our patch is wreaking havoc with my teams build system due to cached node modules.

**Comment by Andarist** [comment]
I've rechecked some things in that PR and I've concluded that it should work and we won't be able to verify this further without shipping this to the users. Hopefully, nothing breaks 🤞 

I still need to recheck the release pipeline since it has been a while since the last release but at least I'm no longer blocked on anything beyond that.

**Comment by Andarist** [comment]
`redux-saga@1.2.0` has been published
