### ISSUE TITLE
Server-side rendering loop for universal sagas

### ISSUE THREAD

**Issue by sompylasar** [redux-saga/redux-saga#331]
I've stumbled upon an issue that has not been discussed yet, and wanted to share my thoughts and get some feedback.

The data flow I'm observing in my app is following:
1. Initial `renderToString` renders `App` component that demands user auth info via dispatch of `ACTION_LOAD_USER_DATA_REQUESTED` in `componentWillMount`, and renders empty because not authenticated yet.
2. `userSaga` takes `ACTION_LOAD_USER_DATA_REQUESTED` and calls the API to load user data.
3. `userSaga` receives the API response and puts `ACTION_LOAD_USER_DATA_SUCCESS`, reducer accepts the user data into the store.
4. Second `renderToString` renders `App` component that renders a `Dashboard` component which demands its own data via dispatch of `ACTION_DASHBOARD_DATA_REQUESTED` in `componentWillMount`, and renders empty because not loaded yet.
5. `dashboardSaga` takes `ACTION_DASHBOARD_DATA_REQUESTED` and calls the API to load dashboard data.
6. `dashboardSaga` receives the API response and puts `ACTION_DASHBOARD_DATA_SUCCESS`, reducer accepts the dashboard data into the store.
7. ... here I should do the third render to render the `App` with non-empty `Dashboard`, which in turn may start to render some components that demand more data.

The above should happen on the server-side to prevent flicker on the browser-side. The demands that should be fulfilled on the browser-side are placed into `componentDidMount`, not `componentWillMount`.

I've come up with the following piece of the server-side rendering code:
https://gist.github.com/sompylasar/5e7157e451f4b7268def9ae1ce01edd4

Welcome for any other ideas how to find out on the server-side, in a generic way (without tying up to the exact components, actions), when all the demands have resolved, and when should I stop re-rendering and send the HTML to the browser.

**Comment by yelouafi** [comment]
From the above I can identify 2 issues:

1. multiple calls to `renderToString` 
2. determine when the server flow have terminated so we can send the HTML to the client

For 2. we can watch for specific events (like `ACTION_LOAD_USER_DATA_SUCCESS` and `ACTION_DASHBOARD_DATA_SUCCESS`) and dispatch `END` once we get all the required events.

For 2. multiple calls to `renderToString` may have noticeable performance issues. In the server, until the flow terminates, we're not interested in the generated markup but only on triggering the component's lifecycle events (esp. `componentWillMount`) so rendering in intermediate calls is wasteful. We need to perform the render only when the flow terminates and we want to send the result to the client. 

On possibility is to use a *custom react renderer* ([here is an example](https://github.com/iamdustan/tiny-react-renderer)) for the intermediate renders which turns `render` calls into no-op. And use `renderToString` only when the server flow terminates. I'm not sure however if we should rely on this feature as it's not officially documented.

another less complicated approach is to simply check for some condition and return `null` from component's `render` method on intermediate calls (Maybe use a HOC for this)

The dependency on components/actions to trigger data fetches comes from the usage of react-router. IMO What we're aiming to (usually) is to load data when a route is activated, but since in react-router we get this information via component lifecycle we trigger data fetches from here.

**Comment by sompylasar** [comment]
@yelouafi Thanks!

> For 2. we can watch for specific events (like ACTION_LOAD_USER_DATA_SUCCESS and ACTION_DASHBOARD_DATA_SUCCESS) and dispatch END once we get all the required events.

We cannot, because there is no component in the architecture that would know them all. The components are decoupled, and the server-side rendering code is generic.

> On possibility is to use a custom react renderer (here is an example) for the intermediate renders which turns render calls into no-op. And use renderToString only when the server flow terminates. I'm not sure however if we should rely on this feature as it's not officially documented.

Yes, thank you, that'd be a good improvement, I'll see if I can do this (later, currently meeting deadlines).

> another less complicated approach is to simply check for some condition and return null from component's render method on intermediate calls (Maybe use a HOC for this)

This would require each component to know that it is a part of that arcitecture, so would require each developer to not forget to put that check in each render. This solution is not scaleable.

> The dependency on components/actions to trigger data fetches comes from the usage of react-router. IMO What we're aiming to (usually) is to load data when a route is activated, but since in react-router we get this information via component lifecycle we trigger data fetches from here.

Actually, Relay follows the same principle. Components demand the data they require to be properly rendered.

**Comment by neurosnap** [comment]
Closing this issue for now.  If you are still interested in discussing then I'd be more than happy to reopen and continue the conversation.  Thanks!
