### ISSUE TITLE
Typo on Real-world example

### ISSUE THREAD

**Issue by juangl** [redux-saga/redux-saga#504]
Am I the only one who realized that Ctrl+W Close tab? I admit I fell. 😢  
![screenshot from 2016-08-24 11-44-11](https://cloud.githubusercontent.com/assets/1887029/17939404/1c5ff33a-69f0-11e6-8fdf-84d5d2ba659b.png)

https://github.com/yelouafi/redux-saga/blob/master/examples/real-world/components/Explore.js#L54

**Comment by pke** [comment]
I am not sure. Isn't that the default key used by redux Devtools?

**Comment by ci5er** [comment]
@pke - it **_is_** the default key on redux-devtools. I'm not sure why, because both on Chrome and FF, Ctrl-W is not caught and closes the tab or, if last tab, the entire browser application. Also, Ctrl-H opens the browser history panel, unless the devtool panel has the focus. I'm not sure what the sense was in either choice, but it is the default...

**Comment by baldwmic** [comment]
good catch @juangl !

anyways, there is better (in my opinion) tooling for redux with https://github.com/zalmoxisus/redux-devtools-extension.

do you think this is still an issue @juangl ?

**Comment by juangl** [comment]
@baldwmic feel free to close this.
