### ISSUE TITLE
[RFC] Supervision strategy for forked tasks (like actor systems)

### ISSUE THREAD

**Issue by slorber** [redux-saga/redux-saga#570]
Hi,

**Edit**: if you are looking for a way to start root sagas, take a look at [this](https://github.com/redux-saga/redux-saga/issues/760#issuecomment-273737022)

@yelouafi we already discussed how close redux-saga looks to me like an actor system. I'm not an expert in actor systems, only know a bit of Akka, so I may say something wrong.
- Actors are organized in trees
- A spawned saga, (or root saga), is like a root actor
- A forked saga, is like a child actor.
- Redux channel is like the actor system event bus

A notable difference between redux-sagas and actor systems is that in actor systems it's currently more easy to handle adhoc communication. A created actor has a reference that can be passed around, and the parent generally hold those references. It's easy for example to send an event:
- Only to the parent (ie the forker saga)
- Only to the childs (ie the forked sagas) (or a subset)
- By "replying" to an incoming event (ie you don't have to know who emitted the event to reply to it) 

I don't know if it's worth implementing this part in Redux-saga yet, until someone has a real usecase for it, but there's also another aspect that Redux-saga does not have that actually would be really helpful: fault tolerance and supervision strategy.

When creating a child actor in Akka (ie forking a saga), you usually define a supervision strategy. The default one is `Escalate` which is somehow similar to the behavior of Redux-saga where the error bubbles-up, and will kill all the actor tree and the childs.

This behavior is fine in simple case, but according to issues and my own experience, it's pretty easy to make your whole app unusable when relying to fork, just because a single request failed. 

I think it would make sense, when forking a task, to define the behavior it should adopt regarding failure.

For example, if Redux-saga had the supervision feature of Akka, on a fork failure, one can choose:
- to propagate the error to the parent saga, which also has its own supervision strategy
- to resume the failing saga (not sure how it's applicable for Redux-saga)
- to restart the failing saga (maybe with an exponential backoff strategy)
- to stop the failing saga, without making the parent and brother sagas know about it

It's also possible to select the appropriate strategy according to the error.

Some Akka doc may be helpful:
- http://doc.akka.io/docs/akka/2.4.1/general/supervision.html
- http://doc.akka.io/docs/akka/snapshot/scala/fault-tolerance.html

So in practice, the idea to fork sagas and automatic cancellation propagation is nice to use. The problem is that the lack of supervision strategy means that we often have to rely on `spawn` instead of `fork` everytime we need some custom fault tolerance strategy, and then we have to manually handle the cancellations which is error-prone.

I think it would be helpful, in practice, to be able to do something like:

``` javascript
yield fork(childSaga,{strategy: "RETRY"})
```

What do you think?

A bit related to https://github.com/yelouafi/redux-saga/issues/543
A SO question: [What is the idiomatic way of starting rootSaga?](http://stackoverflow.com/q/39438005/82609)

**Comment by michaelgilley** [comment]
Interesting idea. I think having the ability to handle errors based on type has some potential need. For instance, one may want to differentiate on a XHR call between a 404 error and a 500. I also liken this to [filtered catch](http://bluebirdjs.com/docs/api/catch.html#filtered-catch) statements in Bluebird's library. 

Since your fork example would just send `{strategy: 'RETRY'}` into the forked saga as the first argument I think you're asking for a separate "actor" effect that might take some kind of options object to configure its operation.

**Comment by yelouafi** [comment]
> It's easy for example to send an event:
Only to the parent (ie the forker saga)
Only to the childs (ie the forked sagas) (or a subset)
By "replying" to an incoming event (ie you don't have to know who emitted the event to reply to it)

You can get a somewhat similar thing using channels. Like in CSP, processes do not interact directly via direct references but through channels. A parent can create a channel and pass it to the child, sending a message only to that child will be done by putting the message on that channel. You can also share a channel between multiple children (cf [channels](http://yelouafi.github.io/redux-saga/docs/advanced/Channels.html) section, `Using channels to communicate between Sagas` shows how to implement load balancing between different tasks using a shared channel).

Perhaps this makes redux-saga an hybrid between actors (do not block on sending messages) and csp (uses channels to communicate), but I dont know if channels have being used before with actors

>but there's also another aspect that Redux-saga does not have that actually would be really helpful: fault tolerance and supervision strategy.

Can't we handle that with just some higher order Saga. For example, a simple `retry` saga can be implemented like

```js
function* retrySaga(saga, args, maxTimes) {
  for(let i = 0; i < maxTimes; i++) {
    try {
      yield call(saga, args)
      return
    } catch(err) {
      continue
    }
  }
}

const retry = (saga, args, maxTimes) => fork(retrySaga, [saga, args, maxTimes])

function* saga() {
   yield retry(takeEvery, ['ACTION'], 5)
   ...
}
```

**Comment by slorber** [comment]
hmmm yes I think I'll implement that myself then :) thanks

Hope to have some time to work on a redux-saga-utils project

**Comment by yelouafi** [comment]
Do you think we should add some configurable helper for this? Or as an option to existing helpers?

**Comment by slorber** [comment]
not sure what you mean by configurable helper :) won't it be the same problem as with takeEvery/takeLatest and require a complex implementation to avoid using generators?

**Comment by yelouafi** [comment]
>not sure what you mean by configurable helper :) 

Didn't have something precise in mind, could be

```js
yield forkWithErrHandler(fn, args, handler)
yield forkRetry()
yield forkIgnore()
...
```

>won't it be the same problem as with takeEvery/takeLatest and require a complex implementation to avoid using generators?

Dont think so; they are basically state machines. Most of the work is alerady done by the [fsmIterator function](https://github.com/yelouafi/redux-saga/blob/master/src/internal/sagaHelpers.js#L9). So it'd be just specifying state transitions (eg see [the throttle helper](https://github.com/yelouafi/redux-saga/blob/master/src/internal/sagaHelpers.js#L79-L96))

**Comment by slorber** [comment]
Hmmm not sure to understand the the fsmIterator nor why it couldn't be applied to takeLatest as well but if you say so why not :)

It would probably be better to provide saga wrappers, like your retry example IMO

**Comment by Andarist** [comment]
`fsm` stands for `finite state machine`. 

`fsmIterator` just wraps passed in map of states and has ability to interpret them later so that resulting `next` function on the created iterator behaves just like the generator-created one. You could say that generator syntax is a sugar allowing you to do the same thing, just in the more pleasant way.

As for state machines - look on the example graph https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Turnstile_state_machine_colored.svg/330px-Turnstile_state_machine_colored.svg.png . Nodes represent states of the machines (traditionally denoted as `q`s) and arrows denote possible transitions between state and next state (correlated with some input ofc, so branching is possible).

Lets look on the simplest example - https://github.com/yelouafi/redux-saga/blob/8a76a1c7eeb97de58072b2e3ab721a59675d0365/src/internal/sagaHelpers.js#L45-L55

According to the `function fsmIterator(fsm, q0, name = 'iterator')` signature `fsm` is map of states which I will describe in the moment. `q0` is a starting state and `name` is just for convenience.

Map of states is an object with state transitions methods which needs to return tuples of `[nextState, yieldedValue, stateUpdater]`. So going back to the `takeEvery` example - `q1` is the starting point of the state machine and it says:
`q1() { return ['q2', yTake, setAction] }` which we could translate to - when transitioned to state `q1` yield `yTake` (just a `{ done, value: take(pattern) }` here), which can be interprated by the saga accordingly, cause `take` is an effect known to the 'puller', and when resumed call `setAction` with resuming value (taken action) and transition to state `q2`.

Handling `q2` is pretty much the same - "when transitioned to this `tuple[0]` state yield `tuple[1]` and when resumed call `tuple[2]` on resuming/injected value".

And this kinda weird `yTake` and `setAction` are there only for keeping things in the scope, available for using by each state.

**Comment by slorber** [comment]
Thanks, I understand better now.

**Comment by granmoe** [comment]
Would something like this work for centralized error handling in all sagas in an app?

```
function* rootSaga () {
  yield sagas.map(saga =>
    spawn(function* () {
      while (true) {
        try {
          yield call(saga)
        } catch (e) {
          console.log(e)
        }
      }
    })
  )
}
```

Or would it possibly cause complex bugs due to scheduling issues internal to redux-saga? I'm wondering if something could get messed up going from the catch back to the try. Assuming this all happens synchronously, there should be no problem, right? Or wrong?

**Comment by slorber** [comment]
I'm simply doing this and it works fine for months:

```javascript
    sagas.forEach(saga =>
      runSaga(saga,reduxSagaIO)
    );
```

**Comment by Andarist** [comment]
could we maybe list various proposals for such strategies? they could be implemented and exposed as functions which simply wraps `fork` effect. However in that case we would have to handle all scenarios internally, so they would have to be constrained to minimum. Upon which somebody could built his own complex strategies.

Basic one would be `detach` and `spawn` could be implemented using it like this
```javascript
const spawn = (...args) => detach(fork(...args))

// in saga
yield detach(fork(someWorker)) // same as yield spawn(someWorker)
```
So that would become just a simple function composition and such functions could be mixed and matched.

WDYT?

**Comment by ajwhite** [comment]
I wanted to chime in with a few things we've been doing in regards to supervision and process monitoring in our application's sagas.

- Keeping forks alive
- Safely performing operations
- Capturing errors for reporting

And recently we've been thinking about how to better manage fault tolerance from a top-down (guardian -> actor) approach.

### Keeping forks alive

```js
yield keepAlive(safelyFork(saga))
```
- `safelyFork` captures and prevents the exception from bubbling
- `keepAlive` restarts the saga if it terminates (important to `join` your forks inside a fork so it doesn't endlessly restart)

### Safely performing operations

Ideally sagas handle and trap their own exceptions. Sometimes we want an exception to be thrown. And sometimes there's unknown exceptions, where a guardian should decide how to handle. 

In the interim while we figure out the best approach, we have "safety" wrappers 

```js
yield forkSafely(saga)
yield callSafely(saga)
```

This is nothing more than a glorified saga instruction with a `try/catch`

### Capturing errors for reporting

In the above cases, we never know if it fails. It's important to detect this for stability improvements. We've added an "interceptor", which catches the sagas error, reports it, and rethrows it

```js
const withFailureReporting = createFailureReporter(errorReportingInstance)

yield callSafely(withFailureReporting(someSaga, 'optional message for the error'))
```

----
To tie it all together, a saga that should remain alive, avoid app-wide takedowns, and report these errors looks like:

```js
const errorReporter = new ErrorReporter('User Saga');
const withFailureReporting = createFailureReporter(errorReporter);

function* sagaThatMayThrow () {
  yield take('FOO');
  if (Math.random() > 0.5) {
    throw new Error('Mock exception');
  }
}

function* saga() {
  yield keepAlive(forkSafely(withErrorReporting(sagaThatMayThrow)))
}
```

**Comment by granmoe** [comment]
@ajwhite How do you address the problem of distinguishing between synchronous and asynchronous exceptions in the "restarter"? If a saga threw a synchronous exception on startup for any reason, and you restarted it, it would keep failing and restarting forever.

**Comment by ajwhite** [comment]
Nope - I've read your proposals in https://github.com/redux-saga/redux-saga/pull/644 though and I think it's important to integrate as a strategy

**Comment by Andarist** [comment]
@ajwhite Really interesting stuff. Need a calm moment to read it again and comment, but I'll be back here with my thoughts for sure!

**Comment by ajwhite** [comment]
I'm going to further culminate my thoughts on the last part. This was kinda a rushed example from the thinking I've done over the past week.

I'll put together a more detailed example and explanation of what the reconciliation process looks like

**Comment by Andarist** [comment]
@ajwhite I think your ideas are really neat and possibly useful for others. Do you plan to share this with others as library?

**Comment by yang-zhang-syd** [comment]
I find to make @granmoe proposed implementation work I need to wrap the `sagas.map()` with all.

```
  yield all(sagas.map(saga => 
    spawn(function* () {
      while(true) {
        try {
          yield call(saga)
          break
        } catch (e) {
          console.log(e)
        }
      }
    })
  ));
```

**Comment by spirobel** [comment]
> I find to make @granmoe proposed implementation working I need to wrap the results of `sagas.map()` with all. Looks like the [document](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/RootSaga.md) is outdated.
> 
> ```
>   yield all(sagas.map(saga => 
>     spawn(function* () {
>       while(true) {
>         try {
>           yield call(saga)
>           break
>         } catch (e) {
>           console.log(e)
>         }
>       }
>     })
>   ));
> ```

can someone explain the purpose of the break statement in the while loop? doesn't it defeat the purpose of the while loop? 
the original code by @granmoe does not have the break statement:
> Would something like this work for centralized error handling in all sagas in an app?
> 
> ```
> function* rootSaga () {
>   yield sagas.map(saga =>
>     spawn(function* () {
>       while (true) {
>         try {
>           yield call(saga)
>         } catch (e) {
>           console.log(e)
>         }
>       }
>     })
>   )
> }
> ```
> 
> Or would it possibly cause complex bugs due to scheduling issues internal to redux-saga? I'm wondering if something could get messed up going from the catch back to the try. Assuming this all happens synchronously, there should be no problem, right? Or wrong?

Kind Regards,
Spirobel :slightly_smiling_face:

**Comment by neurosnap** [comment]
Greetings!  This GH issues is quite a few years old and at this point in time we are primarily focused on maintaining backwards compatibility.  As a result, I'm going to close the issue for now.  I'd be more than happy to reopen this issue if people are still interested in the ideas and want to contribute to the discussion.

Thanks!
