### ISSUE TITLE
Omit "saga has been cancelled" printout in browser console

### ISSUE THREAD

**Issue by williamgranli** [redux-saga/redux-saga#614]
Is there any way to disable this? I'm triggering it manually with 'yield cancel(saga)' so I don't see the point of it being printed by default... 

Thanks for any help!

**Comment by Andarist** [comment]
It's `console.info`, so you can easily filter it out, also its `dev` only

**Comment by aikoven** [comment]
IMO it's still not very convenient. Cancellation is a regular situation, nothing like uncaught exceptions, so I don't think it should be logged. Also you can actually see it in Saga Monitor if you need.

**Comment by williamgranli** [comment]
@Andarist I understand that, but I think there should be an option to not log cancellations, since it's a common practice as @aikoven suggests. Especially since the biggest(?) react boilerplate project (https://github.com/mxstbr/react-boilerplate) uses saga injections which means that sagas have to be cancelled on every route change. 

Wouldn't it be better to f.e. send in an extra param to the cancel like so:
> yield cancel(sagaName, {log: true});

**Comment by slorber** [comment]
I agree that in my project it creates some useless logging statements.

However they are still useful when something is going wrong and you want to debug sagas without plugging the monitor :)

**Comment by yelouafi** [comment]
should we make the logging opt-in?

**Comment by aikoven** [comment]
It would be nice if this could also be configured per generator. 

Also, not sure if it was proposed already, it'd be great if we could supply a custom `displayName` for generators, different from `generator.name`, to be shown in these log messages as well as saga monitor. Would be useful for higher order generators. Setting `Function.name` doesn't work on some browsers.

**Comment by Andarist** [comment]
Sorry that it took so long to act on this in any way.

What I would propose for now is - console.log only non-cancel cancellations (what a mumbo jumbo). What I mean is that we can distinguish why the cancelation has happened - is it user induced via `cancel` effect (no logging should take place) or is it cancel caused by cancel propagation when something throws (logging should take place in dev mode).

@aikoven 
I like your `displayName` idea, will try to explore this. Would be also useful for overriding display name for helper effects like `takeEvery` as its implemented as mere `fork(takeEveryHelper)`, would be cool to omit `fork` part out of this.

**Comment by aikoven** [comment]
> or is it cancel caused by cancel propagation when something throws

+ for this, we could also group these messages to more clearly indicate where the error originated and to which cancellations it lead.

> Would be also useful for overriding display name for helper effects like takeEvery

Actually I have a lot of higher order sagas / custom effects, both could benefit from this. For now I'm using this:
```js
function setFunctionName(func, name) {
  try {
    Object.defineProperty(func, 'name', {
      value: name,
      configurable: true,
    });
  } catch (e) {
    // ignore
  }

  return func;
}
```
But it only works on Chrome AFAIK.

**Comment by Andarist** [comment]
> for this, we could also group these messages to more clearly indicate where the error originated and to which cancellations it lead.

More trickier, but may be doable, gonna try this when I have time!

> Actually I have a lot of higher order sagas / custom effects, both could benefit from this.

Could you share some of your ideas for higher order sagas / custom effects? Just names, not necessarily the code. I think it would be cool to expose the idea more to the audience by making a section of the docs about those 2.

As to higher order sagas I didnt do much of them in my app but like 1 or 2 became really handy, especially `trailingThrottle` and `takeEveryBetween`. Didnt have chance (or need) to write custom effects though other than some specified higher order functions returning regular `take`, like `takeResponse` (from websocket connection).

**Comment by aikoven** [comment]
> Is there any particular reason you are using defineProperty here instead of just assigning?

If I remember correctly, assignment didn't have any effect at all.

> Could you share some of your ideas for higher order sagas / custom effects?

Sure! The one higher order saga I use most is [`bindAsyncAction`](https://github.com/aikoven/redux-typescript-actions/issues/5#issuecomment-270115375), where *async action* is actually a set of three actions: `started`, `done` and `failed`. The returned generator first `put`s `started`, then `call`s the source generator, then `done` or `failed` depending on the result. Useful when you want to track the execution of your worker in reducers.

Another one, `runBetween`, runs given generator between two given actions, i.e. starts with the first action and cancels with the second. I use it for processes that should be run only when user is logged in. Of course I could just start these processes from the saga that controls log-in and user session, but there are a lot of them and I wanted to decouple.

I use custom effect for subscriptions to remote data updates, works like this:
```js
const task = yield subscribe(modelName, filters, worker)
```
Worker gets updates through a channel that it receives as argument. The task has a special cancellation logic that sends unsubscribe request to the server.

One more custom effect / helper is `listenState(selector, worker)`, which invokes `worker` once selected state slice changes.

As we discussed before, I think that *custom effects* and *helpers* like `takeEvery` are basically the same concept. I can't think of anything that couldn't be expressed as a composition of built-in effects. Therefore each of them is just a convenience function returning `call`, `fork` or whatever else effect.

**Comment by Andarist** [comment]
Yeah, ive kinda have ended yesterday with the same conclusion - there is not really that much gain of custom effects as they tend to be achievable with higher order sagas in most cases. 

There are those rare occasions when its hard to implement things with higher order sagas alone. For example your context feature. Although the easier version without dynamic scoping could be also easy implemented with a module keeping your context in a closure.

Also its not possible for now to have a forking worker (started due to call effect) which would return its result immediately when ending itself.

Although those custom effects are rather rarily needed it would still be cool to have a way of extending the core and built-ins.

Im now also wondering if moving helpers to the effects was a good idea (cc @yelouafi). It might be a good idea to move them out of there (again... :/) and create a separate module called 'helpers' (higher-order sagas is really a long name). Plus obviously spend more time in the docs about the idea of higher order sagas, so people understand the concept and dont be confused about separation of those and effects.

Nice ideas with your examples! Is listenState implemented using take('*')?

**Comment by aikoven** [comment]
> Is listenState implemented using take('*')?

Yep:
```js
function* listenState(selector, worker) {
  let prevValue = undefined;

  while (true) {
    yield take('*');

    const value = yield select(selector);

    if (value !== prevValue)
      yield spawn(worker, value, prevValue);

    prevValue = value;
  }
}
```

**Comment by 3plusalpha** [comment]
I agree, that printing out should be optional. Would love to see my console less polluted :)

**Comment by codepunkt** [comment]
Same here. When developing, i have the browser devtools open most of the time. When switching from one route in my app to another, i tend to see a few hundred cancelled logs of websocket/firebase subscirptions, which really slows navigation down.

**Comment by Andarist** [comment]
That's certainlt something that should be done. Ive added `help wanted` label. Maybe somebody would like tackle this? I can help with explaining the source code, but hadnt time to sit down and fix this yet (and probably wont in the nearest future).

**Comment by baldwmic** [comment]
@Andarist I've started this with #945 but could use some help with determining when a cancel is caused by error propagation (if I understand the new approach correctly)

**Comment by bradennapier** [comment]
Any update on this?  When I hot reload during development this gets pretty obnoxious.

![image](https://user-images.githubusercontent.com/15365418/27889952-a84397c4-61a4-11e7-842a-c99eb8eda5ed.png)

**Comment by baldwmic** [comment]
@bradennapier it is definitely annoying. i started a pr here: redux-saga/redux-saga/pull/945

unfortunately, i am not working on this at the moment. would you like to pick up where i left off?

**Comment by axelson** [comment]
As a work-around for this in Chrome devtools you can filter your logs to not include these logs. Filter for `/^((?!has been cancelled).)*$/` which is a regex that excludes lines with `has been cancelled`.

**Comment by Andarist** [comment]
https://github.com/redux-saga/redux-saga/commit/f4b52b04eb6bb9094ab07661c98178b55b401a85

Gonna fo a release in a moment.
