### ISSUE TITLE
Saga triggered in yield map loop only executes once

### ISSUE THREAD

**Issue by tauren** [redux-saga/redux-saga#630]
Really enjoying redux-saga, but I'm running into a problem while using `yield myArray.map`. I have simplified the sagas from my app to illustrate:

```
export function * listCamerasFlow () {
  while (true) {
    const {deviceId} = yield take(CAMERA_LIST_REQUEST)
    let cameras = [{ id: '1', deviceId }, { id: '2', deviceId }]
    yield put(cameraListReady(cameras))
    yield cameras.map(camera => put(cameraSnapshotRequest(camera.deviceId, camera.id)))
    console.log('CAMERAS', cameras)
  }
}

export function * cameraSnapshotFlow () {
  while (true) {
    const request = yield take(CAMERA_SNAPSHOT_REQUEST)
    console.log('GOT REQUEST', request)
    // yield put(cameraSnapshotReady('yo'))
    console.log('DONE')
  }
}

export function * root () {
  yield fork(listCamerasFlow)
  yield fork(cameraSnapshotFlow)
}
```

And here are the action creators:

```
export const cameraSnapshotRequest = (deviceId, cameraId) => {
  console.log('ACTION', cameraId, deviceId)
  return {
    type: CAMERA_SNAPSHOT_REQUEST,
    deviceId,
    cameraId
  }
}

export const cameraSnapshotReady = (imageURL) => ({
  type: CAMERA_SNAPSHOT_READY,
  imageURL
})
```

When `CAMERA_LIST_REQUEST` comes in, the following is logged to the console. Note that `GOT REQUEST` and `DONE` are logged twice (as expected):

```
ACTION 1 644ffd5d-ee45-45dd-95ef-7efc5b6218f1
ACTION 2 644ffd5d-ee45-45dd-95ef-7efc5b6218f1
GOT REQUEST Object {type: "app/CAMERA_SNAPSHOT_REQUEST", deviceId: "644ffd5d-ee45-45dd-95ef-7efc5b6218f1", cameraId: "1"}
DONE
GOT REQUEST Object {type: "app/CAMERA_SNAPSHOT_REQUEST", deviceId: "644ffd5d-ee45-45dd-95ef-7efc5b6218f1", cameraId: "2"}
DONE
CAMERAS [Object, Object]
```

However, if I uncomment `yield put(cameraSnapshotReady('yo')`:

```
export function * cameraSnapshotFlow () {
  while (true) {
    const request = yield take(CAMERA_SNAPSHOT_REQUEST)
    console.log('GOT REQUEST', request)
    yield put(cameraSnapshotReady('yo'))   // <---- added this line
    console.log('DONE')
  }
}
```

I now get the following logged to the console:

```
ACTION 1 644ffd5d-ee45-45dd-95ef-7efc5b6218f1
ACTION 2 644ffd5d-ee45-45dd-95ef-7efc5b6218f1
GOT REQUEST Object {type: "app/CAMERA_SNAPSHOT_REQUEST", deviceId: "644ffd5d-ee45-45dd-95ef-7efc5b6218f1", cameraId: "1"}
CAMERAS [Object, Object]
DONE
```

Notice that `GOT REQUEST` and `DONE` are only logged one time. The second `put` within `yield cameras.map` is called since `ACTION 1` shows up. But `cameraSnapshotFlow` seems to only get one `take`. Also, `DONE` comes after `CAMERAS` in the second scenario.

Is there something simple I'm doing wrong? Any ideas why this is not working?

**Comment by tauren** [comment]
By the way, the same thing happens if I use a `for` loop to sequence the yields:

```
for (let i = 0; i < cameras.length; i++) {
  yield put(cameraSnapshotRequest(cameras[i].deviceId, cameras[i].id))
}
```

**Comment by tauren** [comment]
I was able to solve this problem by using `actionChannel`:

```
export function * cameraSnapshotFlow () {
  const chan = yield actionChannel(CAMERA_SNAPSHOT_REQUEST)
  while (true) {
    const request = yield take(chan)
    console.log('GOT REQUEST', request)
    yield put(cameraSnapshotReady('yo'))
    console.log('DONE')
  }
}
```

However, I'm unclear why this was necessary and if this is the correct way to solve the problem.

**Comment by Andarist** [comment]
Yes, `actionChannel` is the correct way to solve the problem or `takeEvery` (depending on a use case). `put`s are scheduled with internal `scheduler` so nested tasks etc are handled correctly. 

The problem lies here that when 1st `put` is being handled `take` reacts to it, meets `put` which is queued internally, not resolved immediately so `take` could be met again, so in the moment of 2nd `put` (from the map) the worker (saga) you wanted to w8 for the dispatched action didnt come to its `take` again.

**Comment by tauren** [comment]
@Andarist Thanks for your answer, it is good to hear I'm on the right path with `actionChannel`. Unfortunately, I'm not totally following your explanation, but I will look deeper into the redux-saga internals to see if I can make more sense of it.

I was under the impression that using **map** (`yield cameras.map(...)`) would allow the requests to be run concurrently. But they seem to run in sequence, which I assume is because `actionChannel` is queuing them. Do I need to use `takeEvery` for them to run concurrently? I thought that's what doing `yield fork(cameraSnapshotFlow)` in the root saga was enabling.

**Comment by Andarist** [comment]
If you want it to be more 'parallel' I think `takeEvery` is the helper to go instead of `actionChannel`.

`yield cameras.map(...)` is starting tasks in parallel, however the 'problem' is a consumer (`take`r) of yours, its not being able to `take` both when you use such construct
```javascript
while (true) {
  const ac = yield take('ACTION')
  yield put({ type: 'SOME_OTHER_ACTION' })
}
```

With `actionChannel` its in fact processing whats been mapped in a 'queue' (FIFO) fashion, cause channel has an underlaying buffer in it.

This would work, if you need it to be more parallelized.
```javascript
yield takeEvery('AC', function* () {
  yield put({ type: 'SOME_OTHER_ACTION' })
})
```

**Comment by yelouafi** [comment]
>I was under the impression that using map (yield cameras.map(...)) would allow the requests to be run concurrently. But they seem to run in sequence,

Since JavaScript is a single threaded language, everything have to run in sequence. But redux-saga schedules puts internally by 'executing' them one after another. 'executing' means that when we execute a `put`, we dont allow another `put` to execute until we exhaust the effects of the currently executing `put`.

In your case, when you yield the array of puts, the first put in the array gets executed atomically (i.e. will delay other puts yielded during its execution). Since your `cameraSnapshotFlow` is issuing a put itself in the middle of the execution of the 1st `listCamerasFlow ...-> cameras.map(...)` put, it will be delayed until all pending puts execute. This means the `cameraSnapshotFlow` will be suspended until the puts of the `cameras.map(...)` array execute. which means it can't take the 2nd put.

Why do we delay the `cameraSnapshotFlow`'s put? Imagine `listCamerasFlow` want to take actions from  `cameraSnapshotFlow`

```js
function * listCamerasFlow () {
  while (true) {
    const {deviceId} = yield take(CAMERA_LIST_REQUEST)
    let cameras = [{ id: '1', deviceId }, { id: '2', deviceId }] 
    yield put(cameraSnapshotRequest(deviceId, cameras[0].id)))
    // here
    yield take(CAMERA_SNAPSHOT_READY)
    console.log('CAMERAS', cameras)
  }
}
```

when `listCamerasFlow` executes the put effect. The `cameraSnapshotFlow` reaction will execute inside the same stack frame of the put. it means when we resume to ` yield take(CAMERA_SNAPSHOT_READY)` the `CAMERA_SNAPSHOT_READY` action has already been dispatched when we were executing the previous put effect. redux-saga delays nested put effects in order to make it possible for them to be taken later like in this case.

Of course in you case `listCamerasFlow` is not interested in taking anything from `cameraSnapshotFlow` but the presence/absence of an interdependence can not be inferred by the library.

**Comment by yelouafi** [comment]
@Andarist In thinking a little about it, actually that seems weird to me. The case above is nothing complicated; just  a Saga dispatching an array of actions, and another Saga reacting to those actions by dispatching an action itself.

**Comment by Andarist** [comment]
@yelouafi what do you mean that its weird?

I think the behaviour is fine, although tricky for newcomers, but having just 1 worker its not so unnatural that it cant handle many takes at once.

**Comment by yelouafi** [comment]
Scheduling is meant to handle non trivial cases in inter-saga communication (like siblings taking from each other, parent taking from its children). 

But the above case is pretty simple and doesn't involve any interdependence. A saga dispatching a list of actions, another saga taking them and dispatching itself an action. The use case could work without scheduling, but the actual scheduling breaks it. That why I said 'weird', scheduling should handle non trivial cases but without breaking more basic cases.

**Comment by Andarist** [comment]
But is it really a basic *broken* case? I think it only looks like one.

`yield arr` is trying to be *parallel*, so assume that every effect in the `arr` is being run in parallel, but there is only a single `worker` w8ing (in parallel) for a dispatched type. Should this single worker be able to `take` i.e. 10 dispatched actions at once? I dont think so, I think its pretty simple reasoning, even when we think about truly parallel systems.

**Comment by yelouafi** [comment]
it does also happens without parallel effects. cf @tauren's 2nd example

```js
for (let i = 0; i < cameras.length; i++) {
  yield put(cameraSnapshotRequest(cameras[i].deviceId, cameras[i].id))
}
```

**Comment by Andarist** [comment]
Oops, closed for a moment by accident.

That scenario with a `for` loop is indeed scarier. Although solving this issue and probably some similar ones in the future would require a robust, non-obvious `scheduler` implementation instead of the present, elegant one. Just wondering if its worth the trouble. 

Javascript is a single threaded language and anyone coding in it must realise its limitations in such situations. Just explaining the behaviour in the docs could maybe be enough?

**Comment by hilkeheremans** [comment]
Hi @Andarist, we have a fairly complex saga structure in one of our apps, and I believe we are also bumping into this. It's rather difficult to track down where exactly it is coming from, but at least your explanation above helps us look in the right direction.

Explaining this in the docs, including some of the cases shown above, would be an excellent idea, IMO. Adding some common patterns to circumvent the issue (eg action channels) would be a great addition as well.

**Comment by yelouafi** [comment]
I marked this as a bug. I'll try to 'fix' the scheduler to make it handle this case (maybe possible). Otherwise we have to document this case and possible workarounds. but I prefer to delay the 2nd solution until we make sure this can't be fixed in the scheduler.

**Comment by Andarist** [comment]
I think this got fixed by the semaphore scheduler quite long time ago (previous December?). If the issue persists please ping me and I will reopen.
