### ISSUE TITLE
Take last action that matches pattern

### ISSUE THREAD

**Issue by romeovs** [redux-saga/redux-saga#768]
I have a bunch of actions that are started via `takeEvery`. They all rely on an access token that is received in my `"ACCESS_TOKEN_RECEIVED"` action.

So most of these actions look like:

```
function * (action) {
  const token = take("ACCESS_TOKEN_RECEIVED")
  // use token ...
}
```

However, I want multiple of these actions to be able to use the same token from `"ACCESS_TOKEN_RECEIVED"`, e.g. the timeline should look like this:

```
o  <-- request token 
|
o  <-- action A starts (immediately blocks on token)
|
o  <-- action B starts (immediately blocks on token)
|
o  <-- receive token
+  --> action A continues with token
+  --> action B continues with token
|
o  <-- action C starts
+  --> actions continues with token (which is already there)
|
o  <-- new token comes in
|
o  <-- action D starts
+  --> actions continues with new token
```

So the actions have a couple of constraints:

- they to block until a first token comes in
- when there is already a token, they don't need to block, just use that token
- when multiple tokens came in, they should always use the last token that came in

Using `take` here does not work, because then only one action will receive the token (e.g. the action is consumed).

Would it make sense to implement something like `peek(pattern)` that until at least on action that matches `pattern` comes in and uses that action, without "consuming" it? If so, how to do that.

Or should I try to implement this flow in a different way?

**Comment by romeovs** [comment]
To better illustrate what I mean I created a [webpackbin](http://www.webpackbin.com/EkHBT6BUG).

The outcome is
```
"ACTION A started"
"REQ_TOKEN"
"ACTION B started"
"GOT TOKEN 1"
"ACTION A continued with TOKEN 1"
"ACTION B continued with TOKEN 1"
"ACTION C started"
"REQ_TOKEN"
"ACTION D started"
"GOT TOKEN 2"
"ACTION C continued with TOKEN 2"
```

While I expect it to be:
```
"ACTION A started"
"REQ_TOKEN"
"ACTION B started"
"GOT TOKEN 1"
"ACTION A continued with TOKEN 1"
"ACTION B continued with TOKEN 1"
"ACTION C started"
"ACTION C continued with TOKEN 1"
"REQ_TOKEN"
"GOT TOKEN 2"
"ACTION D started"
"ACTION D continued with TOKEN 2"
```

**Comment by granmoe** [comment]
I think you need to build up the actions you are currently receiving via takeEvery into an unlimited buffer. Then when you get "ACCESS_TOKEN_RECEIVED", do your logic for each of these buffered actions.

https://redux-saga.github.io/redux-saga/docs/api/index.html#actionchannelpattern-buffer

Then look at the `flush` example below it:

```
function* saga() {
  const chan = yield actionChannel('ACTION')

  try {
    while (true) {
      const action = yield take(chan)
      // ...
    }
  } finally {
    const actions = yield flush(chan)
    // ...
  }

}
```

Seems like what you want is to take all actions from your channel until a token is received, then process all the actions (like the `finally` block up there) via `flush`.

**Comment by granmoe** [comment]
I'm not sure what the default buffer given to actionChannel is, though. You might have to specify an expanding one:

https://redux-saga.github.io/redux-saga/docs/api/index.html#buffers

**Comment by romeovs** [comment]
@granmoe I see what you mean, but doing it like that makes it hard for me to add new actions that depend on the token, since I would need to DD them all through this `actionChannel`, which makes the code harder to evolve.

But your talk about `Channels` gave me an idea though. I can implement a `LastChannel` that is a special `Channel` that holds only the last action that was `put` to it:

```js
import { END } from 'redux-saga'

export default class LastChannel {
  constructor () {
    this.callbacks = []
  }
  
  // put notifies all takers
  put (message) {
    this.message = message
    for (const callback of this.callbacks) {
      callback(this.message)
    }
    this.callbacks = []
  }
  
  // take registers a new taker
  // if there was already a message, just use that one.
  // If not, wait for the first on to arrive
  take (callback) {
    if (this.message) {
      callback(this.message)
    } else {
      this.callbacks.push(callback)
    }
  }
  
  // close notifies waiting takers with END
  close () {
     for (const callback of this.callbacks) {
      callback(END)
    }
    this.callbacks = []
  }
  
  // flush flushes all the remaining messages (of which 
  // there are none, because only the last one is saved).
  flush () {}
}
```

If I use this in the [webpackbin](http://www.webpackbin.com/EkHBT6BUG), I get the correct output.

I'm not sure if there are any tradeoffs here though...

**Comment by Andarist** [comment]
You can use the custom channel approach, but I think the `flush` method could be still useful for some cases in the future when you know that the remembered token needs to be discarded as its outdated or whatever.

As to having this channel kinda globally - well if this is shared state you will always have to pass it around somehow, so I dont think its avoidable, you only can chose the approach to do so - export it, pass it downwards with each generator or maybe possibly use [the context feature](https://github.com/redux-saga/redux-saga/pull/735) if it makes to the core.

As to your `peek` generator. Passing `pattern` is not supported when `take`-ing from `channel`. Its only possible when you `take` from the `dispatch`ed actions. So passing a type there wont have any effect, you can only make smth like `peek(channel)`.

You could also try to implement some higher order saga like `withToken`, which would look smth like:
```javascript
function* takeEveryWithToken(pattern, worker, ...args) {
	let token

	yield fork(function* () {
		while (true) {
			({ token } = yield take('TOKEN_RECEIVED'))
		}
	}) 

	return yield fork(function* () {
		while (true) {
			const ac = yield take(pattern)
			yield fork(worker, ...args, token, ac)
		} 
	})
}
```

Although it might be better to share a single `channel` inside this closure there, so you set up only 1 listener for `pattern` instead of 1 per each task started with `takeEveryWithToken`.

cc @yelouafi 
this shows that because `channel`s and `buffer`s are implemented using closures (which i really am fan of!) they are no possible for any type of extensions. Every custom `channel`/`buffer` needs to be rebuild from scratch unfortunately. Any ideas what could be made about this? Is it worth to make something about this?

**Comment by Andarist** [comment]
Going to close this, if you have any further questions - please just ask :)

**Comment by romeovs** [comment]
No, this has been helpful. Thanks!
