### ISSUE TITLE
tips on refactoring codebase for sagas

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#867]
Much of our async logic is moving slowly into sagas, but there is now significant duplication.

I notice that there are times that I'd like to incorporate some of the logic in our actionCreators without doing a full refactor

Furthermore, a full refactor (where all actionCreators just emit plain objects) also seems like too much. We could conceivably use thunks to handle some initial, existing logic rather than going all-in with saga side-effect handling

Has anyone else encountered a similar issue? If so, how did you handle them?

**Comment by Andarist** [comment]
Hard to tell without any code snippets. Could u show some problematic fragments?

**Comment by reem** [comment]
I recently migrated a redux-thunk-driven codebase to redux-saga, so I can relate to your issues. My primary recommendation is that you move as much logic over as possible to sagas as soon as possible. Remember, a saga is just a function, so you can always move over your redux-thunk code wholesale to sagas in what is basically an automatic transformation into a watcher saga + just calling your thunk.

You can then begin refactoring the sagas and thunks themselves to be more idiomatic (using call instead of just running side effects, etc.), but you won't have a problem where half of your logic can't talk to the other half.

**Comment by anthonychung14** [comment]
This makes sense. Some examples

1. A lengthy 100 line thunk that talks with multiple APIs
2. Logic in thunks that mutate data before sending it to the reducer

I ended up moving them over piecemeal
Also. I totally missed PUT.RESOLVE. I didn't know you could plug thunks into sagas.

Great API (provided I read the docs right haha)
