### ISSUE TITLE
Can redux-saga block/transform actions?

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#872]
I've noticed something about sagas:

namely, their side-effects do not complete before new state is calculated after an action is dispatched.

in my experience...
```

store = 0;

dispatch({
    type: 'ADD_ONE'
})

function* watchStore() {
    while (true) {
        yield take('ADD_ONE');
        const state = yield select();
        console.log(state, '1 or 0?');
    }
}
```

the saga would console.log(1, '1 or 0') because state is calculated first

-------------

1. is this true for all cases?

2. can sagas be written in a way that they intercept and transform/block an action (namely, before state is re-calculated)?

**Comment by neurosnap** [comment]
The results of the reducers are always calculated before the saga gets activated: https://github.com/redux-saga/redux-saga/blob/master/src/internal/middleware.js#L78

The only way I know to block or intercept an action is to create a custom middleware.

There is another callback you can hook into which is the `sagaMiddleware.emitter` option (https://github.com/redux-saga/redux-saga/blob/master/src/internal/middleware.js#L59, https://redux-saga.github.io/redux-saga/docs/api/index.html#createsagamiddlewareoptions) but that's not going to help you intercept an action because that function gets called after the reducers as well.

I've never needed the ability to intercept an action before it hits the reducer within a saga before, what use case are you thinking about?

**Comment by anthonychung14** [comment]
we're handling in-app permissioning, so while there can be a valid login, certain types will have access to certain views/actions.

I didn't use a higher-order-component + routing solution since this mostly works as a SPA, which makes certain actions (not routes) permissioned

**Comment by granmoe** [comment]
@anthonychung14  I think you could easily do this via a custom middleware. You'd probably want to add thunk middleware to your project (if you haven't already) so that you can easily dispatch further actions if necessary in the middleware. Then create your permissions middleware and if the user does not have permission to do something, do not feed the action to the next middleware (don't call `next(action)`), but instead fire some actions to notify the user (or whatever you want to do) and just return the store (or state...can't remember what middleware is supposed to ultimately return). Obviously, the real security for your app will live on backend, so this is all probably just to customize the UI based on the kind of user.

**Comment by Andarist** [comment]
> The results of the reducers are always calculated before the saga gets activated: https://github.com/redux-saga/redux-saga/blob/master/src/internal/middleware.js#L78

That's true if you put sagaMiddleware last in your chain or when or whole chain is sync, but if you put some async middleware in between reducers and sagaMiddlewre then your saga will be called before new state has been computed.

However that's rather unintended and I advise to put `sagaMiddleware` as the last one.
