### ISSUE TITLE
Use select effect in normal function/eventChannel

### ISSUE THREAD

**Issue by PriyankBhatt** [redux-saga/redux-saga#899]
I am using redux sagas event channel. I have a specific use case where i want to getStore state when event gets triggered as eventChannel is not generator function i am not able to use select effect of redux sagas. Any other way to achieve this 

```
function subscribe(socket) {
    return eventChannel(emit => {
        socket.subscribe(listenerTopic, {qos: 1});
        socket.on('reconnection', () => {
            // i need to fetch latest unread message, for that i need to get timestamp
           // for last message received which is in store so the command will be to 
         // send sinceDate i.e last message timestamp and untilDate that is currentDate
   })
}
```

**Comment by visweshs** [comment]
I don't think you can select state in the event channel, because it's not a generator function and thus can't yield on any effects.

In the parent (I.e where you're creating the channel):
1) Select the substate
2) Create the channel by passsing in the substate as an argument to the channel creator function
3) If this substate changes, cancel the original event channel and recreate the channel with the new substate

Note this approach might potentially have a performance overhead if the relevant substate changes often; you will be constantly reconstructing channels.

**Comment by Andarist** [comment]
Well, you create this channel by passing a socket to it as argument. That mean you can send an event through it from the outside (even in the saga). `eventChannel` is not bidirectional by design (maybe thats a valid use case though? cc @yelouafi) so you cannot send anything to it.

But you can emit from its inside a command, which can be interpreted by a channel consumer so it eventually could send a message through socket.

**Comment by baldwmic** [comment]
I'm translating what @Andarist wrote in words into code. What do you think @PriyankBhatt ?

```
...
// in eventchannel subscriber
socket.on('reconnection', () => {
  emit({ type: 'reconnection' });
})
...

...
// in channel consumer
const channel = yield call(subscribe, socket);
while (true) {
  const event = yield take(channel);
  if (event.type === 'reconnection') {
    const latestUnreadMessage = yield select(getLatestUnreadMessage);
    // do something
  }
}
...
```

in interest of code brevity, i've left out some of the function definitions, but I think the gist is there
