### ISSUE TITLE
Dispatching actions from Redux DevTools suddently doesn't trigger sagas

### ISSUE THREAD

**Issue by sglocastic** [redux-saga/redux-saga#903]
Everything worked as expected until one emulator load. Now actions dispatched by the code work as intended but everything I dispatch from devTools doesn't trigger any saga.
```
"redux-saga": "^0.14.3",
"remote-redux-devtools": "^0.5.7",
"remote-redux-devtools-on-debugger": "^0.7.0",
"remotedev-server": "^0.3.0-beta-3"
```

**Comment by Andarist** [comment]
Did it work before? Is it some sort of regression? Or just something you have noticed now? Thanks for reporting.

**Comment by sglocastic** [comment]
It worked flawlessly before a couple of days. I can't pinpoint exactly when this started to happen. I did not change any versions or upgrade.

I tried to find a method or a way to dispatch an action from chrome console but with no success. I couldn't find anything useful in those properties that Redux devTools attaches to window.

**Comment by Andarist** [comment]
If you didn't upgrade `redux-saga` I assume the changed behaviour is not a result of our code.

Maybe @zalmoxisus could shed some light on it

**Comment by zalmoxisus** [comment]
There are 2 ways you can use [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools):

1. As a store enhancer ([importing as default](https://github.com/zalmoxisus/remote-redux-devtools#add-devtools-enhancer-to-your-store)). In this case Redux DevTools enhancer is not aware of other enhancers, because they are applied before. So, the dispatched actions from teh monitor will not trigger sagas.
2. As a custom composer (importing [`composeWithDevTools`](https://github.com/zalmoxisus/remote-redux-devtools#use-devtools-compose-helper)), which is a workaround to solve this Redux limitation. In this case it should trigger sagas.

Do you use the second approach? I guess, you accidentally imported `default` from `remote-redux-devtools`. If not, could you please share a repro?

**Comment by sglocastic** [comment]
Yeah, it is imported as a store enhancer. I will implement it as a custom composer tomorrow and let you know if it solves the problem.

**Comment by zalmoxisus** [comment]
@sglocastic, a PR to amend the README on [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools) would be much appreciated.

**Comment by stjepangolemac** [comment]
@zalmoxisus  It is done. Here is the [pull request](https://github.com/zalmoxisus/remote-redux-devtools/pull/76). It's sglocastic, but from other account.

**Comment by Andarist** [comment]
Great that it end up with improved README, good work!
