### ISSUE TITLE
TakeLatest being called multiple times 

### ISSUE THREAD

**Issue by christopherdiehl** [redux-saga/redux-saga#917]
If I exit my React container (change routes) and go back to the container that has the saga then takeLatest is fired twice. If I do it three times then it is called three times.

Ex: I have a React container **foo** that has a function that watches for an action **bar** and calls another function **createProduct** using takeLatest. I leave foo, go to another page, then come back to foo. When the action **bar** is dispatched, the function **createProduct** is fired twice.

Super basic saga/ action code I am using below.

Does anyone know why the function createProduct is being called as often as the container has been visited?

Saga:
```
/*default saga*/
export function * watchCreateProduct() {
  yield takeLatest(CREATE_PRODUCT,createProduct);
}
/*saga that does stuff*/
export function* createProduct() {
  console.log('CREATING PRODUCT');
}
```

Action that dispatches type CREATE_PRODUCT:

```
export function createProduct(product) {
  return {
    type: CREATE_PRODUCT,
  };
}
```

**Comment by baldwmic** [comment]
From the API docs, [takeLatest](https://github.com/redux-saga/redux-saga/tree/master/docs/api#takelatestpattern-saga-args) `Spawns a saga on each action dispatched to the Store that matches pattern. And automatically cancels any previous saga task started previous if it's still running.`

The key thing to understand is that each time you dispatch the `CREATE_PRODUCT` action, your `createProduct` saga will be run. The only exception to this is if you dispatch a second `CREATE_PRODUCT` action before the first saga task is completed. However, since your `createProduct` saga is only logging to the console, it will probably finish very quickly. Meaning, if I understand correctly, that your `CREATE_PRODUCT` action is dispatched each time your React route changes.

So, just to clarify, it sounds like you are entering the route for your React container that dispatches `CREATE_PRODUCT`, and then the first `createProduct` saga task is run and completes. Then you go to another route, and then come back to the same route that dispatches `CREATE_PRODUCT` again, which causes a second new `createProduct` saga task to run and complete. If this is the case, then this is not a bug, but expected behavior. @christopherdiehl can you confirm that this is what is happening?

**Comment by Andarist** [comment]
I think @christopherdiehl is starting his sagas based on routes and once he comes back to the same route he starts new `takeLatest(...)` task. In such a scenario you need to discard a previously started/injected saga when some `LOCATION_CHANGE` occurs or something

**Comment by christopherdiehl** [comment]
Hello all, I'm only calling CREATE_PRODUCT on a button press. In my testing, I am also making sure that the `createProduct` saga has finished before pressing the button once again. 

@Andarist is correct, I am starting `watchCreateProduct()` when the route loads. I believe that the previously injected saga is discarded. If it helps any, I'm using [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/).

**Comment by baldwmic** [comment]
@christopherdiehl it would be most helpful if you could post a [webpackbin](https://www.webpackbin.com/) of your problem in order to be able to debug what exactly is going on. could you do that?

**Comment by Andarist** [comment]
@christopherdiehl could u describe how do u load sagas on route changes? Im pretty much confident that this is the case and it simply isnt geting discarded automatically for u when you leave the root.

**Comment by christopherdiehl** [comment]
Here is a sample route in my `routes.js` file.

    ```
}, {
      path: '/foo',
      name: 'Foo',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/Foo/reducer'),
          System.import('containers/Foo/sagas'),
          System.import('containers/Foo'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('resetPassword', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }, {
```

**Comment by christopherdiehl** [comment]
Update, if I leave the enter and exit the container 3 times without calling the action, then enter again and call the action the function `createProduct` is called 4 times.

**Comment by Andarist** [comment]
ive seen exactly this way used by others, so its fine :)
