### ISSUE TITLE
test select effect with ava

### ISSUE THREAD

**Issue by adamgajzlerowicz** [redux-saga/redux-saga#927]
How do I test select effect please? I just spent a full day trying to figure this out, but no luck. Here is what I came up with 
```
function* loadData() {
    const foo = yield select((state) => {
        return state.foo.value;
    });

    console.log('foo is :', foo);
}
```
and the test:
```
test.only('Data saga', t => {
    const generator = loadData();
    console.log(generator.next({foo: 'blah'}).value);
});
```

but I always get inside of my generator value `undefined` 

Can you help please?

**Comment by baldwmic** [comment]
@adamgajzlerowicz it seems like your selector is looking for an [object property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects) that doesn't exist in the test `state` object, hence why the log prints `undefined`.

Changing your selector to return the following should work
```
return state.foo
```

Calling [`next`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/next) on a generator returns an object with two properties, `value`, and `done` which is why your test uses `.value`

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
