### ISSUE TITLE
[Question] How to handle subscription/unsubscription of _lots_ of websocket events

### ISSUE THREAD

**Issue by codepunkt** [redux-saga/redux-saga#932]
Hello everyone.

In my current project, i'm dealing with firebase websocket subscriptions. Different components can subscribe to different data, e.g. in a list of items every ListItem component subscribes to a websocket "event" for that specific item by dispatching a `SUBSCRIBE` action in `componentDidMount` and unsubscribes by dispatching an `UNSUBSCRIBE` action in `componentWillUnmount`.

My sagas look like this:

```javascript
const subscriptions = {}

export function * subscribeLoop () {
  while (true) {
    const { path } = yield take(SUBSCRIBE)
    subscriptions[path] = yield fork(subscription, path)
  }
}

export function * unsubscribeLoop () {
  while (true) {
    const { path } = yield take(UNSUBSCRIBE)
    yield cancel(subscriptions[path])
  }
}

export function * subscription (path) {
  let ref

  try {
    const updateChannel = channel()

    ref = api.child(path)
    ref.on('value', snapshot => {
      updateChannel.put(snapshot.val())
    })

    while (true) {
      const data = yield take(updateChannel)
      yield put(handleUpdate(path, data))
    }
  } finally {
    if (yield cancelled()) {
      ref.off()
      ref = null
    }
  }
}
```

I assume this is not the right way to deal with this - it is indeed rather slow on a list of 500 items.
How can i optimize the performance?

- Do i even need to fork?
- Should i introduce some kind of delay to give the thread some space to handle other things?

Any hints are appreciated.

**Comment by Andarist** [comment]
Can u pin point what is slow?

**Comment by bradennapier** [comment]
@codepunkt hey there - i have an example of firebase specifically with my [redux-saga-process](https://github.com/Dash-OS/redux-saga-process) package.  You may gain some insight from taking a look.  

I actually register hundreds if not thousands of firebase listeners without any problem using this package with automatic handling of listeners / cancelling.  

The example shows a few things:

1. Listening and waiting until firebase should startup
2. Importing the firebase package dynamically so that we take advantage of code splitting
3. Registering listeners via redux actions

[Firebase Examples](https://github.com/Dash-OS/redux-saga-process/tree/master/examples/firebase)

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
