### ISSUE TITLE
Yielding `put` effects in an external saga

### ISSUE THREAD

**Issue by eliseumds** [redux-saga/redux-saga#951]
Hi everyone,

I'm running a standalone saga inside a `redux-connect` decorator before rendering a page (server-side):

```js
import { runSaga } from 'redux-saga';

@connectData(({ store }) => {
  return runSaga(store, loadPage).done;
})
class Page extends Component { ... }
```

and I'd like to yield some put effects inside it, but I get the following exception:

```
[server] stdout: redux-saga error: uncaught at loadPage
TypeError: Cannot read property '@@redux-saga/SAGA_ACTION' of undefined
    at Array.<anonymous> (/mypath/node_modules/redux-saga/lib/internal/channel.js:189:16)
    at dispatch (/mypath/node_modules/redux/lib/createStore.js:186:19)
    at /mypath/node_modules/react-router-redux/lib/middleware.js:22:18
    at /mypath/node_modules/redux-saga/lib/internal/middleware.js:72:22
    at /mypath/build/bm/server.js:64744:18
    at /mypath/node_modules/redux-saga/lib/internal/utils.js:265:12
    at /mypath/node_modules/redux-saga/lib/internal/proc.js:480:52
    at exec (/mypath/node_modules/redux-saga/lib/internal/scheduler.js:26:5)
    at flush (/mypath/node_modules/redux-saga/lib/internal/scheduler.js:67:5)
    at asap (/mypath/node_modules/redux-saga/lib/internal/scheduler.js:40:5)
    at runPutEffect (/mypath/node_modules/redux-saga/lib/internal/proc.js:477:25)
    at runEffect (/mypath/node_modules/redux-saga/lib/internal/proc.js:432:220)
    at next (/mypath/node_modules/redux-saga/lib/internal/proc.js:314:9)
    at currCb (/mypath/node_modules/redux-saga/lib/internal/proc.js:386:7)
    at runSelectEffect (/mypath/node_modules/redux-saga/lib/internal/proc.js:689:7)
    at runEffect (/mypath/node_modules/redux-saga/lib/internal/proc.js:432:941)
    at next (/mypath/node_modules/redux-saga/lib/internal/proc.js:314:9)
    at proc (/mypath/node_modules/redux-saga/lib/internal/proc.js:269:3)
    at runSaga (/mypath/node_modules/redux-saga/lib/internal/runSaga.js:59:33)
```

Again: this only happens when I yield `put` effects. Any idea of what's going on? Is it an expected behaviour?

**Comment by Andarist** [comment]
Hm, according to this
`    at /mypath/node_modules/redux-saga/lib/internal/middleware.js:72:22`
the code is going through the `middleware`  somehow and reaching [this](https://github.com/redux-saga/redux-saga/blob/df9d18472bf442f323517c215abe32846c2dfd5f/src/internal/channel.js#L162) with no `input` (action).

Aint sure how is it happening, would have to see more code - reproduced issue on something like  `webpackbin` would be very helpful

**Comment by eliseumds** [comment]
@Andarist my apologies. I had tried without middlewares before, and the error persisted. Here goes a demo: https://codesandbox.io/s/lYgzmnkNj

**Comment by Andarist** [comment]
Ok, so I've looked into ur issue. Saga's `subscribe` option is not equivalent to the redux one. It was a surprise for me when I once have learnt about it too ;)

You can see what is passed as it in `sagaMiddleware.run` API [here](https://github.com/redux-saga/redux-saga/blob/afcf5d4f9557b850a04f56177d3ecfa94b837098/src/internal/middleware.js#L49). And read more about its signature [here](https://redux-saga.js.org/docs/api/index.html#runsagaoptions-saga-args)

When you subscribe to the redux store its callback wont provide [any arguments](https://github.com/reactjs/redux/blob/a226034ec26898aedcbf2c547d7578bb2722e641/src/createStore.js#L178) to you, it only notifies you that 'something happened'. 

On the other hand redux-saga needs dispatched actions as input to its subscribe to resolve `take` effects. Therefore its signature is slightly different from redux one.

I hope this explanation shows what the problem is, if not - dont hesitate, ask more questions :)

**Comment by eliseumds** [comment]
Thanks for the investigation. If I understood it correctly, it means that I have these two alternatives:

* Access the `sagaMiddleware` in my `@connectData`, then run it `sagaMiddleware.run(mySaga)`
* Store the latest action in the Redux state and pass a modified subscribe function to `runSaga`:

```js
runSaga({
  subscribe: cb => {
    return store.subscribe(() => {
      cb(store.getState().latestAction);
    });
  },
  dispatch: store.dispatch,
  getState: store.getState
}, mySaga)
```

Does that make sense?

**Comment by Andarist** [comment]
Yeah, pretty much. I would advise ubti to for the first one. Its more reasonable to use sagaMiddleware.run anyway if you connect it to the actual store.

You can enhance ur store so its easier to access it. Somehow like:
const store = {
  ...createStore(...),
  runSaga: sagaMiddleware.run,
}

**Comment by eliseumds** [comment]
Sweet! I appreciate the hep, @Andarist.
